### ISSUE TITLE
Make clean rules

### ISSUE THREAD

**Issue by mjhsieh** [PacificBiosciences/pitchfork#127]
1. do-clean
2. do-bleach
3. do-uninstall

**Comment by mjhsieh** [comment]
Clean means cd $(WRKSRC) && make distclean / or make clean

**Comment by mjhsieh** [comment]
Bleach means rm -rf $(WRKSRC)

**Comment by mjhsieh** [comment]
Use (future pitchfork) command to uninstall

**Comment by pb-cdunn** [comment]
1.5. do-distclean

And isn't there a 'develop' folder too?

**Comment by mhsieh** [comment]
We don't but we probably should have one.

**Comment by mhsieh** [comment]
do-clean/do-distclean/do-flush are done in ports/thirdparty need more attention to ports/python and ports/pacbio.

**Comment by mjhsieh** [comment]
now all ports have some sort of clean rules.Waiting for master Makefile

**Comment by mhsieh** [comment]
Master Makefile clean-* sort of works now.
