### ISSUE TITLE
I HAVE boost installed.

### ISSUE THREAD

**Issue by mjhsieh** [PacificBiosciences/pitchfork#128]
1. How to check boost version / validate boost
2. Use HAS_BOOST for the variable name

**Comment by pb-cdunn** [comment]
As for dot, I think we should expect users to run a configure-script first. It would not be a good idea to use **make** as a programming language, and it *is* a good idea to store in a transparent way the decisions which have been made up front by detecting the O/S, existing libraries, etc. The cost is that users must run one extra command before running **make**; the benefits are multiple.

**Comment by dalexander** [comment]
I agree that it's best to have a separate configure script to pre-initialize things

**Comment by mhsieh** [comment]
HAVE_BOOST is now in the mjhsieh branch

**Comment by mjhsieh** [comment]
Need a way to specifying boost lib to accommodate future project dependencies.

**Comment by pb-cdunn** [comment]
Do you mean the boost-version? Or the directory?

**Comment by mhsieh** [comment]
the version of the boost header.

**Comment by mjhsieh** [comment]
version 1.55 works on blasr but not pblaa

**Comment by mjhsieh** [comment]
the version check is now in trunk branch.
