### ISSUE TITLE
pip install --editable

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pitchfork#142]
* http://stackoverflow.com/questions/30306099/pip-install-editable-vs-python-setup-py-develop

This is *very* important for packages under development. Another big win is that we can `git pull` without having to reinstall.

We only need this for our own packages. And note that it's broken for **FALCON** (because of how the extension-modules are built), so FALCON needs a special exception. Otherwise, this can be on-always, or a user-configuration. But it is *very important*! I would add it myself, but I don't want to clobber ongoing work.

**Comment by mhsieh** [comment]
this seems to work in master for ports/pacbio python packages
