### ISSUE TITLE
Come up with a clear recommendation for incremental development

### ISSUE THREAD

**Issue by mhsieh** [PacificBiosciences/pitchfork#147]

**Comment by pb-cdunn** [comment]
For developers:

    pip install -e

In general, library owners should avoid altering the API. That is something Scott has talked about.

**Comment by mhsieh** [comment]
done for ports/pacbio/...

**Comment by pb-cdunn** [comment]
Beyond Python, symlinks would be helpful, instead of staging, where possible. For now, I have to remember to remove the corresponding sentinel in `PREFIX/var/pkg`.

**Comment by mhsieh** [comment]
indeed, let me file another bug.
