### ISSUE TITLE
abandon uninstallation mechanism or simplify it.

### ISSUE THREAD

**Issue by mhsieh** [PacificBiosciences/pitchfork#150]

**Comment by pb-cdunn** [comment]
:+1:

**Comment by pb-cdunn** [comment]
Note that simply designed libs/execs can be uninstalled easily. E.g. libblasr_cpp should put all its headers under a single directory within `PREFIX/include`. So you can simply:

    cd ${PREFIX}/include; rm -rf blasr
    cd ${PREFIX}/lib; rm -f libpbihdf* libalignment* ...

(In fact, I think I fixed blasr recently to use two levels, so its 3 sub-modules would not have overlapping header-install directories, but for now other libraries might still depend on the non-hierarchical headers.)

So it might be better for uninstall to be *ad hoc*, only when needed. Then the automated use of a staging area for discovery of the installation isn't needed. That's more in line with the pitchfork philosophy anyway

**Comment by mhsieh** [comment]
still not simple enough.

**Comment by mhsieh** [comment]
`bin/pitchfork uninstall foo` now works.
