### ISSUE TITLE
OSX does not have -lrt

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pitchfork#155]
ld: library not found for -lrt

We need to inject that, depending on the O/S. Or modify blasr/configure.py.

**Comment by pb-cdunn** [comment]
**cmake** is the problem. It should detect this if it has any value at all. **configure.py** already handles this for all the non-cmake blasr builds.

Some people use `FindLibrt.cmake`. Nothing is simple for **cmake**.

Apparently blasr's cmake files need conditional `target_link_libraries()`. I'll try to find something better...

**Comment by pb-cdunn** [comment]
One interesting solution: Use **clang** on Linux. Its `libc++.so` always links `librt.so`, so the problem is solve! Haha. Probably not practical for us though.

**Comment by mhsieh** [comment]
So is Mac port broken at the moment?

**Comment by pb-cdunn** [comment]
For blasr, yes. It's much better to fix the problem than to create a patch. blasr is the only thing broken.

Maybe bax2bam/bam2bax should not be in blasr. Hmmmmm.....
