### ISSUE TITLE
pitchfork ccache is not compatible with USC biocluster

### ISSUE THREAD

**Issue by mhsieh** [PacificBiosciences/pitchfork#208]
@yunfeiguo points out ccache doesn't work under usc student account. This might be a problem with the type of filesystem used.

**Comment by mhsieh** [comment]
https://github.com/PacificBiosciences/blasr_libcpp/issues/138#issuecomment-199557108

**Comment by mhsieh** [comment]
My recommendation is to add this to your settings.mk file under pitchfork:
```
CCACHE_DIR  = /tmp/yunfeiguo.ccache
```

**Comment by yunfeiguo** [comment]
Could you tell me where that file is? I couldn't find it. Thanks.

**Comment by mhsieh** [comment]
if pitchfork is cloned at /foo/bar/pitchfork, you can create a file /foo/bar/pitchfork/settings.mk so you don't have to type some super long command like `make PREFIX=/home/yunfeiguo/Downloads/mybuild CCACHE_DIR=/tmp/yunfeiguo.ccache`.

See [the wiki](https://github.com/PacificBiosciences/pitchfork/wiki#its-possible-to-specify-meaningful-paths-for-the-have_-variables-in-settingsmk)

**Comment by yunfeiguo** [comment]
Got it. Thanks!

**Comment by yunfeiguo** [comment]
Yes! Installation was successful. Sorry I forgot to say it. Thanks!
