### ISSUE TITLE
add smrtflow to pitchfork

### ISSUE THREAD

**Issue by mhsieh** [PacificBiosciences/pitchfork#223]
https://github.com/PacificBiosciences/smrtflow/issues/14
1. sbt
2. <work>
3. profit!

**Comment by mpkocher** [comment]
```
$> cd smrtflow
$> sbt smrt-analysis/pack 
$> export PATH=$(pwd)/smrt-analysis/target/pack/bin:$PATH
$> fasta-to-reference --help
```

The scala tools should now be accessible from `smrflow/smrt-analysis/target/pack/bin`

Also, the tools require java 1.8.

**Comment by mhsieh** [comment]
merged the feature - https://github.com/PacificBiosciences/pitchfork/pull/224 , Michael please verify if you got time, no rush.

**Comment by mpkocher** [comment]
Thanks
