### ISSUE TITLE
Remove log compile time lintr from build

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/pitchfork#248]
This line:

https://github.com/PacificBiosciences/pitchfork/blob/master/ports/pacbio/pbcommandr/Makefile#L34

```echo 'install.packages("lintr",      repos="http://cran.r-project.org")' >> $(_WRKSRC)/install-pbbamr.R```

and associated bits should be removed.  The static analyzer can't help once deployed and it greatly increases the install time.

**Comment by mhsieh** [comment]
4c66335

**Comment by mhsieh** [comment]
https://github.com/PacificBiosciences/pitchfork/pull/249

**Comment by mhsieh** [comment]
https://github.com/PacificBiosciences/pitchfork/pull/251
