### ISSUE TITLE
pitchfork won't build blasr

### ISSUE THREAD

**Issue by amckinlay** [PacificBiosciences/pitchfork#258]
I need bax2bam in the blasr package but had trouble compiling bax2bam separately. Instead, I opted to try using pitchfork to build blasr. Unfortunately, I run into a compilation problem. I believe I have all the dependencies of pitchfork installed so I'm posting an issue here.

GCC:
```
[mckinlay.andrew@i21a-s2 pitchfork]$ gcc --version
gcc (GCC) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
`settings.mk`:
```
[mckinlay.andrew@i21a-s2 pitchfork]$ cat settings.mk
## What we use internally
PREFIX        = /dev/shm/pitchfork_build
WORKDIR       = /dev/shm/pitchfork_wd
#HAVE_CCACHE   = /opt/software/c/ccache/3.2.3/bin/ccache
#HAVE_ZLIB     = /opt/software/z/zlib/1.2.8-cloudflare
##             For OSX, ZLIB can be installed to /usr via xcode-select --install
#HAVE_PYTHON   = /opt/python-2.7.9/bin/python
#HAVE_OPENBLAS = /opt/software/o/openblas/0.2.14
#HAVE_BOOST    = /opt/software/b/boost/1.58
#HAVE_CMAKE    = /opt/software/c/cmake/3.2.2/bin/cmake
#HAVE_HDF5     = /opt/software/h/hdf5-tools/1.8.12
#
## Contributed by @cwarden45 (with ccache, boost, and hdf5 installed via osx homebrew) 
#PREFIX      = /opt/pacbio
#WORKDIR     = /opt/pitchfork
#HAVE_PYTHON = /usr/local/bin/python
#HAVE_CMAKE  = /usr/local/bin/cmake
#HAVE_CCACHE = /usr/local/Cellar/ccache/3.2.3/bin/ccache
#HAVE_BOOST  = /usr/local/Cellar/boost/1.60.0_1/include
#HAVE_HDF5   = /usr/local/Cellar/hdf5/1.8.16_1
```
Make:
https://gist.github.com/amckinlay/6f1afcae126efba73f932d9466da832f

**Comment by mhsieh** [comment]
Hi,
    This is very fascinating, why would boost try to build bz2lib support (and failed)? Do you have bzip2-devel installed? Also please let us know what linux distribution/version are you using.

Thanks,
--mj

**Comment by mhsieh** [comment]
On the other hand, try skipping building boost with HAVE_BOOST variables in the settings.mk file.

**Comment by amckinlay** [comment]
@mhsieh Made it a little further this time. https://gist.github.com/amckinlay/d85b05aeab3e9bf111ab4a16e6507d7f

`settings.mk`:
```
[mckinlay.andrew@i21a-s2 pitchfork]$ cat settings.mk
## What we use internally
PREFIX        = /dev/shm/pitchfork_prefix
WORKDIR       = /dev/shm/pitchfork_wd
#HAVE_CCACHE   = /opt/software/c/ccache/3.2.3/bin/ccache
#HAVE_ZLIB     = /opt/software/z/zlib/1.2.8-cloudflare
##             For OSX, ZLIB can be installed to /usr via xcode-select --install
#HAVE_PYTHON   = /opt/python-2.7.9/bin/python
#HAVE_OPENBLAS = /opt/software/o/openblas/0.2.14
HAVE_BOOST    = /apps/gcc/5.2.0/boost/1.60.0
#HAVE_CMAKE    = /opt/software/c/cmake/3.2.2/bin/cmake
#HAVE_HDF5     = /opt/software/h/hdf5-tools/1.8.12
#
## Contributed by @cwarden45 (with ccache, boost, and hdf5 installed via osx homebrew) 
#PREFIX      = /opt/pacbio
#WORKDIR     = /opt/pitchfork
#HAVE_PYTHON = /usr/local/bin/python
#HAVE_CMAKE  = /usr/local/bin/cmake
#HAVE_CCACHE = /usr/local/Cellar/ccache/3.2.3/bin/ccache
#HAVE_BOOST  = /usr/local/Cellar/boost/1.60.0_1/include
#HAVE_HDF5   = /usr/local/Cellar/hdf5/1.8.16_1
```

**Comment by amckinlay** [comment]
@mhsieh
```
[mckinlay.andrew@i21a-s2 pitchfork]$ lsb_release -d
Description:	Red Hat Enterprise Linux Server release 6.7 (Santiago)
```

**Comment by mhsieh** [comment]
Do you have python 2.7 installed somewhere?

**Comment by mhsieh** [comment]
The reason for the crash is due to the fact that blasr_libcpp configuration requires python2.7, but redhat 6 uses python2.6 as default, presumably you have python2.7 installed in /usr/local, do this:
```bash
PATH=/usr/local/bin:$PATH make blasr
```

**Comment by pb-cdunn** [comment]
Well, the `commands` module exists in python-2.6. It was removed in python-3, so maybe that's being used. **pitchfork** could run `python2.7` explicitly, but I think `python2.6` would work too. (Not certain.)

You need to track this down first:

    'import site' failed; use -v for traceback

That might be a trapped error, but it's definitely an error. Something is wrong.

**Comment by amckinlay** [comment]
I tried a different Python and it worked! Funnily, retaining the built-in Python 2.6.6 allowed the build to succeed. While setting up pitchfork, I loaded a Graphviz module which pulled in Python 2.7.6 instead.

While the software is built, I am considering trying `HAVE_PYTHON` to force the use of the OS Python while the other modules remain loaded. Hopefully this will confirm it was the Python module at fault. I could then try pitchforking with a Python 2.7.6 build from scratch.

On another note, why does building `bax2bam` require `blasr` or the "libblasr" in the first place?

**Comment by mhsieh** [comment]
Dear Andrew,
    Chris is right, if 2.6 python was used, configure.py would be still working. You can see which python were you using before running make by `which python` command.

I don't think HAVE_PYTHON will allow you to re-use python 2.6.x.

Best,
--mj

**Comment by pb-cdunn** [comment]
> On another note, why does building bax2bam require blasr or the "libblasr" in the first place?

**bax2bam** and **bam2bax** are currently hosted in the **blasr** repo. I think it links with **blasr_libcpp**, but I'm not sure.
