### ISSUE TITLE
trying -> make PREFIX=/foo/bar blasr

### ISSUE THREAD

**Issue by entzn** [PacificBiosciences/pitchfork#261]
I get the following errors
entzn@ausress9810] pitchfork $ sudo make PREFIX=/foo/bar blasr
make -f mk/init.mk init
make[1]: Entering directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork'
/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/bin/checkSystem
[ERROR] unable to run git, consider doing yum install git
make[1]: *** [sanity] Error 1
make[1]: Leaving directory`/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork'
make: **\* No rule to make target `initialized.o', needed by`ccache'.  Stop.

did 
yum install git
downloaded and unpacked - ccache-3.2.4

same error for - make

**Comment by mhsieh** [comment]
I will need to know: the output of `lsb_release -d` and the output of `which git`

**Comment by mhsieh** [comment]
and do not use sudo for pitchfork: do this instead:
```
sudo mkdir /foo/bar
sudo chown entzn /foo/bar
make PREFIX=/foo/bar blasr
```
if you are satisfied the outcome, you can later do `sudo chown root:wheel -R /foo/bar`

**Comment by etnzn** [comment]
[entzn@ausress9810] pitchfork $ lsb_release -d
Description:    Red Hat Enterprise Linux Server release 6.8 (Santiago)
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ which git
/tools/general/bin/git
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ sudo mkdir /foo/bar
mkdir: cannot create directory `/foo/bar': No such file or directory
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ sudo mkdir /foo/bar
mkdir: cannot create directory `/foo/bar': No such file or directory
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ sudo mkdir -p /foo/bar
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ sudo chown entzn /foo/bar
[entzn@ausress9810] pitchfork $ make PREFIX=/foo/bar blasr
make -f mk/init.mk init
make[1]: Entering directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork'
/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/bin/checkSystem
/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/bin/checkCC gcc
[ERROR] unexpected program error in /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/bin/checkCC
make[1]: *** [sanity] Error 1
make[1]: Leaving directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork'
make: *** No rule to make target `initialized.o', needed by `ccache'.  Stop.
[entzn@ausress9810] pitchfork $

**Comment by pb-cdunn** [comment]
Make the 2nd line of `pitchfork/bin/checkCC`

    set -vx

Then try again.

**Comment by etnzn** [comment]
same error after edit to checkCC
[entzn@ausress9810] pitchfork $ make PREFIX=/foo/bar blasr
make -f mk/init.mk init
make[1]: Entering directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork'
/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/bin/checkSystem
/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/bin/checkCC gcc
++ gcc -dumpversion
[ERROR] unexpected program error in /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/bin/checkCC
make[1]: *** [sanity] Error 1
make[1]: Leaving directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork'
make: *** No rule to make target `initialized.o', needed by `ccache'.  Stop.
[entzn@ausress9810] pitchfork $

**Comment by pb-cdunn** [comment]
Something is wrong with `gcc -dumpversion`, but we don't know what because stderr was suppressed:
```

**Comment by pb-cdunn** [comment]
Are you neglecting to copy some output? When I run (with `set -vx` and a fake CC) I see this:
```
$ PREFIX=/home/UNIXHOME/cdunn/fubar/pf CC=ls make -f mk/init.mk init
/home/UNIXHOME/cdunn/fubar/pitchfork/bin/checkSystem
/home/UNIXHOME/cdunn/fubar/pitchfork/bin/checkCC ls

reportVersion(){
    set -euf -o pipefail
    $1 -dumpversion 2>&1
}

die(){
    test "$*" && echo "$*" || true
    exit 1
}

CC=`echo $* | awk '{print $1}'`
echo $* | awk '{print $1}'
++ echo ls
++ awk '{print $1}'
+ CC=ls

which $CC >& /dev/null || die "[ERROR] $CC is not on your PATH env variable"
+ which ls

# check the c++11 availability
case $CC in
gcc*)
  myVersion=`reportVersion $CC`
  if $CC -v 2>&1|grep ' version '|grep Apple >& /dev/null; then
      (echo 3.3 && echo $myVersion)|sort -t.    -k1,2|head -1|grep 3.3 >& /dev/null && exit 0
  else
      (echo 4.8 && echo $myVersion)|sort -t.    -k1,2|head -1|grep 4.8 >& /dev/null && exit 0
  fi
  ;;
clang*)
  myVersion=`reportVersion $CC`
  (echo 3.3 && echo $myVersion)|sort -t. -k1,2|head -1|grep 3.3 >& /dev/null && exit 0
  ;;
icc*)
  myVersion=`reportVersion $CC`
  (echo 11.0.0 && echo $myVersion)|sort -t. -k1,2|head -1|grep 11.0.0 >& /dev/null && exit 0
  ;;
*)
  die "[ERROR] unrecognized CC, please send us info if you think this CC is valid"
  ;;
esac
+ case $CC in
+ die '[ERROR] unrecognized CC, please send us info if you think this CC is valid'
+ test '[ERROR] unrecognized CC, please send us info if you think this CC is valid'
+ echo '[ERROR] unrecognized CC, please send us info if you think this CC is valid'
[ERROR] unrecognized CC, please send us info if you think this CC is valid
+ exit 1
```

**Comment by pb-cdunn** [comment]
Try `make -v`. Let's see what version of GNU make you are running. (I use `3.81`)

**Comment by mhsieh** [comment]
Hi @etnzn,
    At first you want to point to the output to `/foo/bar` but you didn't have `/foo` directory first, did you really mean to `mkdir /foo/bar` ? Nonetheless try `mkdir -p /foo/bar` then.

Personally I would use /opt/mypacbio to store the pitchfork build artifact.

**Comment by mhsieh** [comment]
By the way, please:
Do `git pull --rebase` under pitchfork directory to get the latest updates.

**Comment by etnzn** [comment]
[entzn@ausress9810] pitchfork $ gcc -dumpversion
4.4.7
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-redhat-linux-gnu
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ git pull --rebase
Cannot pull with rebase: You have unstaged changes.
Please commit or stash them.
[entzn@ausress9810] pitchfork $

[entzn@ausress9810] pitchfork $ git commit -m "chg to set -vm" ./bin/checkCC
[master ac75456] chg to set -vm
 Committer: Keith McWhite <entzn@ausress9810.na.agrogroup.net>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 1 file changed, 3 insertions(+), 2 deletions(-)
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ git pull --rebase
remote: Counting objects: 144, done.
remote: Compressing objects: 100% (137/137), done.
remote: Total 144 (delta 67), reused 0 (delta 0), pack-reused 2
Receiving objects: 100% (144/144), 27.51 KiB | 0 bytes/s, done.
Resolving deltas: 100% (67/67), done.
From https://github.com/PacificBiosciences/pitchfork
   655da2b..d4fb51b  master     -> origin/master
 * [new branch]      R_refactor_0.001 -> origin/R_refactor_0.001
 * [new branch]      centos7issues -> origin/centos7issues
 * [new branch]      dontupgradepip -> origin/dontupgradepip
First, rewinding head to replay your work on top of it...
Applying: chg to set -vm
[entzn@ausress9810] pitchfork $

**Comment by mhsieh** [comment]
Please use a newer gcc version (newer or as new as 4.8.0) instead of hacking checkCC

**Comment by etnzn** [comment]
[entzn@ausress9810] pitchfork $ module load gcc
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ which gcc
/tools/general/app/gcc-4.8.5/bin/gcc
[entzn@ausress9810] pitchfork $

**Comment by etnzn** [comment]
[entzn@ausress9810] pitchfork $ module load gcc
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ which gcc
/tools/general/app/gcc-4.8.5/bin/gcc
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ make PREFIX=/tmp/pitchfork blasr

[SNIP-OF-ENDPOINT]
find /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/samtools-0.1.20 ! -type d|awk -F '/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/samtools-0.1.20/' '{print $2}' > /tmp/pitchfork/var/pkg/samtools-0.1.20
make[1]: Leaving directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/ports/thirdparty/samtools'
make -C ports/thirdparty/cmake do-install
make[1]: Entering directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/ports/thirdparty/cmake'
/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/bin/pitchfork fetch --url https://cmake.org/files/v3.4/cmake-3.4.1.tar.gz
fetching https://cmake.org/files/v3.4/cmake-3.4.1.tar.gz
md5sum -c MD5SUM || exit
cmake-3.4.1.tar.gz: OK
tar zxf cmake-3.4.1.tar.gz -C /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace
(cd /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/cmake-3.4.1 && ./bootstrap --prefix=/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/cmake-3.4.1) >& config.log || /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/bin/diewith config.log
make -C /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/cmake-3.4.1 >& build.log || /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/bin/diewith build.log
rm -rf /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/cmake-3.4.1
make -C /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/cmake-3.4.1 install >& install.log || /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/bin/diewith install.log
cd /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/cmake-3.4.1 && tar cf - * | tar xf - -C /tmp/pitchfork
find /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/cmake-3.4.1 ! -type d|awk -F '/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/cmake-3.4.1/' '{print $2}' > /tmp/pitchfork/var/pkg/cmake-3.4.1
make[1]: Leaving directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/ports/thirdparty/cmake'
make -C ports/pacbio/htslib do-install
make[1]: Entering directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/ports/pacbio/htslib'
git clone git://github.com/PacificBiosciences/htslib /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/htslib
Cloning into '/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/htslib'...
fatal: Unable to look up github.com (port 9418) (Name or service not known)
make[1]: *** [/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/htslib] Error 128
make[1]: Leaving directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/ports/pacbio/htslib'
make: *** [htslib] Error 2
[entzn@ausress9810] pitchfork $

**Comment by mhsieh** [comment]
Keith,
    This is interesting: is for some reason your git suddenly broke?
```
fatal: Unable to look up github.com (port 9418) (Name or service not known)
```

What's your output of `which git`, `git --version`, and `nslookup github.com` in this node? Please add some description, like sentences, too. :-)

CC @JeanQin

**Comment by etnzn** [comment]
here it is...
[entzn@ausress9810] pitchfork $ which git
/tools/general/bin/git
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ git --version
git version 2.4.8
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ nslookup github.com
Server:         10.82.129.27
Address:        10.82.129.27#53

** server can't find github.com: NXDOMAIN

[entzn@ausress9810] pitchfork $

**Comment by mhsieh** [comment]
Hi Keith, You might want to contact your local network administrator to see: is the domain name server working?

**Comment by etnzn** [comment]
Tried to run 'make' again....

[entzn@ausress9844] pitchfork $ make PREFIX=/tmp/pitchfork blasr
make -C ports/thirdparty/ccache do-install
make[1]: Entering directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/ports/thirdparty/ccache'
rm -rf /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4
make -C /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/ccache-3.2.4 prefix=/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4 install >& install.log || /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/bin/diewith install.log
cd /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4/bin && ln -sfn ccache `basename gcc`
cd /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4/bin && ln -sfn ccache `basename g++`
cd /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4/bin && ln -sfn ccache `basename gfortran`
cd /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4/bin && ln -sfn ccache cpp
cd /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4/bin && ln -sfn ccache CC
cd /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4 && tar cf - * | tar xf - -C /tmp/pitchfork
find /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4 ! -type d|awk -F '/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4/' '{print $2}' > /tmp/pitchfork/var/pkg/ccache-3.2.4
/bin/bash: /tmp/pitchfork/var/pkg/ccache-3.2.4: No such file or directory
make[1]: *** [/tmp/pitchfork/var/pkg/ccache-3.2.4] Error 1
make[1]: Leaving directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/ports/thirdparty/ccache'
make: *** [ccache] Error 2
[entzn@ausress9844] pitchfork $

**Comment by etnzn** [comment]
I crated a pitchfork directory off   /tmp - then ran -> make PREFIX=/tmp/pitchfork blasr

[entzn@ausress9844] pitchfork $ pwd
/tmp/pitchfork
[entzn@ausress9844] pitchfork $
[entzn@ausress9844] pitchfork $ ls -Flart
total 16
drwxr-xr-x.  4 entzn bioinfo 4096 Jul 15 20:51 ./
drwxr-xr-x.  3 entzn bioinfo 4096 Jul 15 20:54 share/
drwxr-xr-x.  2 entzn bioinfo 4096 Jul 15 20:54 bin/
drwxrwxrwt. 13 root  root    4096 Jul 15 21:00 ../

**Comment by mhsieh** [comment]
Hi, You can try `make _startover` before you restart a new compilation.

**Comment by etnzn** [comment]
The command ' make_startover '  = not found

[entzn@ausress9810] pitchfork $ pwd
/tools/bioinfo/app/blasr_install/pitchfork
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ ls -Flart
total 96
drwxr-xr-x   5 entzn bioinfo  4096 Jun 24 17:04 ../
-rw-r--r--   1 entzn bioinfo 11358 Jun 24 17:04 LICENSE
-rw-r--r--   1 entzn bioinfo   531 Jun 24 17:04 README.md
-rw-r--r--   1 entzn bioinfo   920 Jun 24 17:04 settings.mk.example
-rw-r--r--   1 entzn bioinfo   962 Jun 24 17:18 settings_bak.mk
-rw-r--r--.  1 entzn bioinfo 13842 Jun 28 13:26 EXmakefile
-rw-r--r--   1 entzn bioinfo  1536 Jun 30 10:56 settings_edited.mk
-rw-r--r--   1 entzn bioinfo   111 Jul  5 12:41 .gitignore
-rw-r--r--   1 entzn bioinfo   696 Jul  5 12:41 .travis.yml
-rw-r--r--   1 entzn bioinfo 13833 Jul  5 12:41 Makefile
drwxr-xr-x   2 entzn bioinfo  4096 Jul  5 12:41 mk/
drwxr-xr-x   6 entzn bioinfo  4096 Jul  5 12:41 ports/
drwxr-xr-x   2 entzn bioinfo  4096 Jul  5 12:41 bin/
drwxr-xr-x   8 entzn bioinfo  4096 Jul  5 12:41 .git/
-rw-r--r--   1 entzn bioinfo     0 Jul  5 14:23 initialized.o
drwxr-xr-x   9 entzn bioinfo  4096 Jul  5 14:40 distfiles/
drwxr-xr-x  10 entzn bioinfo  4096 Jul  5 14:53 workspace/
drwxr-xr-x  10 entzn bioinfo  4096 Jul 15 16:27 ./
drwxr-xr-x.  4 entzn bioinfo  4096 Jul 15 16:27 deployment/
drwxr-xr-x   9 entzn bioinfo  4096 Jul 15 17:05 staging/
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ make_startover
-bash: make_startover: command not found
[entzn@ausress9810] pitchfork $

**Comment by etnzn** [comment]
Cannot get any MAKE commands to run successfully:
make PREFIX=/tmp/pitchfork blasr
make configure-submodule
make build-submodule
make blasr
[entzn@ausress9810] pitchfork $ make configure-submodule
make: *** No rule to make target `configure-submodule'.  Stop.
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ make build-submodule
make: *** No rule to make target `build-submodule'.  Stop.
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $ make blasr
make -C ports/thirdparty/ccache do-install
make[1]: Entering directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/ports/thirdparty/ccache'
rm -rf /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4
make -C /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/ccache-3.2.4 prefix=/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4 install >& install.log || /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/bin/diewith install.log
cd /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4/bin && ln -sfn ccache `basename gcc`
cd /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4/bin && ln -sfn ccache `basename g++`
cd /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4/bin && ln -sfn ccache `basename gfortran`
cd /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4/bin && ln -sfn ccache cpp
cd /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4/bin && ln -sfn ccache CC
cd /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4 && tar cf - * | tar xf - -C /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/deployment
find /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4 ! -type d|awk -F '/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/staging/ccache-3.2.4/' '{print $2}' > /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/deployment/var/pkg/ccache-3.2.4
/bin/bash: /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/deployment/var/pkg/ccache-3.2.4: No such file or directory
make[1]: *** [/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/deployment/var/pkg/ccache-3.2.4] Error 1
make[1]: Leaving directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/ports/thirdparty/ccache'
make: *** [ccache] Error 2
[entzn@ausress9810] pitchfork $
[entzn@ausress9810] pitchfork $

**Comment by mhsieh** [comment]
1. pitchfork doesn't do submodule, you are doing it wrong, don't mix instruction between projects.
2. there is a space between "make" and "_startover"

Judging from the quality of communication we have in the past, I am afraid that we might need to lower the priority of this github issue.

**Comment by etnzn** [comment]
Hi - I actually typed --> "make startover" --> I just sent a "literal copy" of your typed make_startover...
I'd really appreciate it if someone can provide insights on the errors and diminish focus on my copy/paste or typing patterns
Based on the documentation - we will be happy if we can get "make blasr" to run

**Comment by mhsieh** [comment]
Hi, the error indicates that you had an unclean cache artifact previously failed when your local domain name server was not working, so my suggestion would be
```
make PREFIX=/tmp/pitchfork _startover
```
PREFIX has to be specified. Alternatively write the line `PREFIX=/tmp/pitchfork` in a settings.mk file.

**Comment by etnzn** [comment]
[entzn@ausress9810] pitchfork $ make PREFIX=/tmp/pitchfork startover
make: *** No rule to make target `startover'.  Stop.
[entzn@ausress9810] pitchfork $

**Comment by etnzn** [comment]
Holding at this step..

[entzn@ausress9810] pitchfork $ make PREFIX=/tmp/pitchfork _startover
rm -f mk//../initialized.o
This will erase everything in /tmp/pitchfork/, staging/ and /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/ directories.
Are you sure? y
+ rm -rf /tmp/pitchfork/bin /tmp/pitchfork/doc /tmp/pitchfork/etc /tmp/pitchfork/include /tmp/pitchfork/lib /tmp/pitchfork/share /tmp/pitchfork/var /tmp/pitchfork/.Python staging/boost-1.60.0 staging/ccache-3.2.4 staging/cmake-3.4.1 staging/hdf5-1.8.16 staging/ncurses-6.0 staging/samtools-0.1.20 staging/zlib-1.2.8 /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/boost-1.60.0 /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/ccache-3.2.4 /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/cmake-3.4.1 /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/hdf5-1.8.16 /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/ncurses-6.0 /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/samtools-0.1.20 /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/zlib-1.2.8 ports/thirdparty/boost/build.log ports/thirdparty/boost/config.log ports/thirdparty/ccache/build.log ports/thirdparty/ccache/config.log ports/thirdparty/ccache/install.log ports/thirdparty/cmake/build.log ports/thirdparty/cmake/config.log ports/thirdparty/cmake/install.log ports/thirdparty/hdf5/build.log ports/thirdparty/hdf5/config.log ports/thirdparty/hdf5/install.log ports/thirdparty/ncurses/build.log ports/thirdparty/ncurses/config.log ports/thirdparty/ncurses/install.log ports/thirdparty/samtools/build.log ports/thirdparty/zlib/build.log ports/thirdparty/zlib/config.log ports/thirdparty/zlib/install.log

**Comment by etnzn** [comment]
command ->  pitchfork $ make PREFIX=/tmp/pitchfork _startover             
Completed with

+ test -d /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/blasr_install/pitchfork/workspace/.git/pip/wheels
make: *** [_startover] Error 1
[entzn@ausress9810] pitchfork $

**Comment by entzn** [comment]
After pitchfork_startover...
https://github.com/PacificBiosciences/pitchfork/issues/261#issuecomment-229799501
Back to error with - checkCC
[entzn@ausress9810] pitchfork $ make PREFIX=/foo/bar blasr
make -f mk/init.mk init
make[1]: Entering directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/pitchfork'
/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/pitchfork/bin/checkSystem
/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/pitchfork/bin/checkCC gcc
++ gcc -dumpversion
[ERROR] unexpected program error in /gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/pitchfork/bin/checkCC
make[1]: *** [sanity] Error 1
make[1]: Leaving directory `/gpfs/rtp/.filesets/biogrid_root/tools/bioinfo/app/pitchfork'
make: *** No rule to make target `initialized.o', needed by `ccache'.  Stop.

**Comment by mhsieh** [comment]
which gcc are you using?

**Comment by mhsieh** [comment]
closed for inactivity
