### ISSUE TITLE
pip cache should be in workspace/.pip

### ISSUE THREAD

**Issue by mhsieh** [PacificBiosciences/pitchfork#262]
since most of the people don't have permission to create `${PREFIX}.pip` . Discuss before I commit.

**Comment by pb-cdunn** [comment]
How about `WORKSPACE/.git/pip`?

**Comment by pb-cdunn** [comment]
Two goals:

1. Avoiding deleting the downloaded eggs and tarballs on a "startover".
2. Share the pip downloads with other pitchfork runs.

(2) is less important than (1). But I'm pretty open to whatever you think is best.

**Comment by mhsieh** [comment]
,git/pip looks hack-y but it's brilliant
