### ISSUE TITLE
[Question] What are the different settings needed in "settings.mk", and what they are for ?

### ISSUE THREAD

**Issue by RxLoutre** [PacificBiosciences/pitchfork#274]
Hi everyone !

I'm trying to use PacBio tools from pitchfork (I wanted to use Quiver in particular).

I followed the installation instructions, I installed almost all packages (pbalign, ConsensusCore, ...), but at some point, it wasn't doing what I expected.

I was trying to see if everything was all good and installed, so I try the following : 

`bin/pitchfork installed`

But it wasn't showing anything at all. So I guess there is something wrong with the settings.mk. 

Well, I see that there is a settings.mk.example that we could get inspired from, but I'm kind of confused with all theses parameters, what they represent, if I need all of them, and what should I use for each one.

Anyone could help me with this ?

Cheers,

Roxane

**Comment by mhsieh** [comment]
Short answer is that you will need to write the setting of PREFIX in the settings.mk for bin/pitchfork to be functional.

**Comment by RxLoutre** [comment]
Yeah, that was the point I get, but I need some advices about what are theses parameters, what they mean...

**Comment by mhsieh** [comment]
Okay .. will do.
