### ISSUE TITLE
Need Unanimity

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pitchfork#276]
PacificBiosciences/GenomicConsensus#104

It works when my path is basically

    /pbi/dept/secondary/builds/mainline/current_smrttools_incremental_installdir/smrtcmds/bin:/pbi/dept/secondary/builds/mainline/current_smrttools_incremental_installdir/private/otherbins/all/bin:...

But it fails when my PATH is from a fresh pitchfork build.

I need help with this. I cannot validate my own code until this is solved.

**Comment by pb-cdunn** [comment]
GenomicConsensus works from tarball, but not from pitchfork.

Armin says we need to use "unanimity". I guess that means we should *not* use some alternative. I'm not sure what that means, but I guess that makes it a **pitchfork** Issue.

**Comment by mhsieh** [comment]
Sorry for the late reply, I am working on it right now.

**Comment by pb-cdunn** [comment]
* https://jira.pacificbiosciences.com/browse/DEP-7

**Comment by mhsieh** [comment]
273fe6a1aa288eead054f1034145fcb7c4b71f74
