### ISSUE TITLE
ConsensusCore2

### ISSUE THREAD

**Issue by zyndagj** [PacificBiosciences/pitchfork#278]
Hello,

Can you make a ConsensusCore2 target for GenomicConsensus to accelerate the polishing process?

Thanks,
Greg Zynda

**Comment by mhsieh** [comment]
Greg, sorry I broke it, let me fix that.

**Comment by mhsieh** [comment]
Actually ConsensusCore2 is now provided by unanimity project, what was the error message Greg?

**Comment by zyndagj** [comment]
No error message, I just noticed that when I built the GenomicConsensus
target, ConsensusCore was pulled as the dependency instead of
ConsensusCore2.

Is unanimity the best way to run Arrow? I am unfamiliar with that project.

**Comment by nlhepler** [comment]
Hi @zyndagj,

Yes, we recently folded the ConsensusCore2 and pbccs projects into a single repository, unanimity, to help us smooth development amongst the highly-interrelated projects. unanimity includes all the same functionality from both, so a `python setup.py install` or `pip install .` from the unanimity source directory will install the python2 ConsensusCore2 package.

Best,

Lance

**Comment by mhsieh** [comment]
The GenomicConsensus built okay locally, I will mark this as question and close this. :-)
