### ISSUE TITLE
pbccs, make error and does not recognise Sequel bam file

### ISSUE THREAD

**Issue by anslan** [PacificBiosciences/pitchfork#280]
Altough Pitchfork Wiki says that pbccs is possible target to build, I got an **ERROR** trying to do it.
**>**git clone git://github.com/PacificBiosciences/pitchfork
**>**cd pitchfork
**>**make pbccs
**make: *** No rule to make target `pbccs'.  Stop.**

As I figured, then pbccs is moved to PacificBiosciences/unanimity? I was able to build it there.
However, when I try to create CCS reads from raw .bam
file from Sequel System, then it says '**[bam_header_read] invalid BAM binary header (this is not a BAM file). [main_samview] fail to read the header from "myinput.subreads.bam**".'

pbccs works fine when I first use bax2bam to create subreads.bam file from bax.h5 files. The problem is that Sequel System does not give bax and bas files. What is the difference between Sequel System created bam and bax2bam created bam files?
(no possibility to create an issue under unanimity)

**Comment by pb-cdunn** [comment]
> (no possibility to create an issue under unanimity)

The unanimity authors have dropped public support, though they are updating the README on who to contact. I guess you could buy a Sequel! :smiley: But you are still free to run the code if you can figure it out.

Anyway, at least it builds for you now. Good luck!
