### ISSUE TITLE
ncurses failed to create symbolic link

### ISSUE THREAD

**Issue by ccali930** [PacificBiosciences/pitchfork#287]
I'm having an issue using pitchfork to install blasr on a linux system (openSUSE 13.2 Harlequin):

```
git clone git://github.com/PacificBiosciences/pitchfork
cd pitchfork
make PREFIX=/tmp/pitchfork blasr
```
Here's the end of the output where I get the error:
```
make[1]: Entering directory '/home/chris/pitchfork/ports/thirdparty/ncurses
rm -rf /home/chris/pitchfork/staging/ncurses-6.0
make -C /home/chris/pitchfork/workspace/ncurses-6.0 prefix=/home/chris/pitchfork                    
/staging/ncurses-6.0 install >& install.log || /home/chris/pitchfork/bin/diewithinstall.log
ln -s libncurses.so /home/chris/pitchfork/staging/ncurses-6.0/lib/libcurses.so
ln: failed to create symbolic link ‘/home/chris/pitchfork/staging/ncurses-6.0/lib/libcurses.so’: No such file or directory
Makefile:44: recipe for target '/tmp/pitchfork/var/pkg/ncurses-6.0' failed
make[1]: *** [/tmp/pitchfork/var/pkg/ncurses-6.0] Error 1
make[1]: Leaving directory '/home/chris/pitchfork/ports/thirdparty/ncurses'
Makefile:176: recipe for target 'ncurses' failed
make: *** [ncurses] Error 2
```
Any help would be appreciated!

-Chris

**Comment by mhsieh** [comment]
Hi Chris,
    It would be nice if you can provide the log files under `/home/chris/pitchfork/ports/thirdparty/ncurses/`, I am guessing that build wasn't 100% successful.

Thanks,

**Comment by ccali930** [comment]
Here they are:

[install.txt](https://github.com/PacificBiosciences/pitchfork/files/482601/install.txt)
[build.txt](https://github.com/PacificBiosciences/pitchfork/files/482606/build.txt)
[config.txt](https://github.com/PacificBiosciences/pitchfork/files/482611/config.txt)

**Comment by mhsieh** [comment]
Okay is your `ln` an alias or some sort of different one? can we do following commands to find out?

```
ls /home/chris/pitchfork/staging/ncurses-6.0/lib/*so*
type ln
```

**Comment by ccali930** [comment]
ls /home/chris/pitchfork/staging/ncurses-6.0/lib/*so*

ls: cannot access /home/chris/pitchfork/staging/ncurses-6.0/lib/*so*: No such file or directory

**Comment by ccali930** [comment]
ln
ln: missing file operand
Try 'ln --help' for more information.

**Comment by ccali930** [comment]
ln --help
Usage: ln [OPTION]... [-T] TARGET LINK_NAME   (1st form)
  or:  ln [OPTION]... TARGET                  (2nd form)
  or:  ln [OPTION]... TARGET... DIRECTORY     (3rd form)
  or:  ln [OPTION]... -t DIRECTORY TARGET...  (4th form)
In the 1st form, create a link to TARGET with the name LINK_NAME.
In the 2nd form, create a link to TARGET in the current directory.
In the 3rd and 4th forms, create links to each TARGET in DIRECTORY.
Create hard links by default, symbolic links with --symbolic.
By default, each destination (name of new link) should not already exist.
When creating hard links, each TARGET must exist.  Symbolic links
can hold arbitrary text; if later resolved, a relative link is
interpreted in relation to its parent directory.

**Comment by mhsieh** [comment]
I meant `type ln` as a command

**Comment by mhsieh** [comment]
And how about `ls /home/chris/pitchfork/staging/ncurses-6.0/lib/` ?

**Comment by ccali930** [comment]
`type ln`
ln is hashed (/usr/bin/ln)

`ls /home/chris/pitchfork/staging/ncurses-6.0/lib/`
ls: cannot access /home/chris/pitchfork/staging/ncurses-6.0/lib/: No such file or directory

**Comment by ccali930** [comment]
The "lib" folder is actually named "lib64". I tried changing this to "lib" and re-running pitchfork but the program automatically changes it back to "lib"

**Comment by ccali930** [comment]
` ls /home/chris/pitchfork/staging/ncurses-6.0/lib64`
libform.a       libmenu.a       libncurses.a      libncurses.so.6    libpanel.so.6
libform_g.a     libmenu_g.a     libncurses++.a    libncurses.so.6.0  libpanel.so.6.0
libform.so      libmenu.so      libncurses_g.a    libpanel.a
libform.so.6    libmenu.so.6    libncurses++_g.a  libpanel_g.a
libform.so.6.0  libmenu.so.6.0  libncurses.so     libpanel.so

**Comment by ccali930** [comment]
`ls /home/chris/pitchfork/staging/ncurses-6.0/lib64/*so*`
/home/chris/pitchfork/staging/ncurses-6.0/lib64/libform.so
/home/chris/pitchfork/staging/ncurses-6.0/lib64/libform.so.6
/home/chris/pitchfork/staging/ncurses-6.0/lib64/libform.so.6.0
/home/chris/pitchfork/staging/ncurses-6.0/lib64/libmenu.so
/home/chris/pitchfork/staging/ncurses-6.0/lib64/libmenu.so.6
/home/chris/pitchfork/staging/ncurses-6.0/lib64/libmenu.so.6.0
/home/chris/pitchfork/staging/ncurses-6.0/lib64/libncurses.so
/home/chris/pitchfork/staging/ncurses-6.0/lib64/libncurses.so.6
/home/chris/pitchfork/staging/ncurses-6.0/lib64/libncurses.so.6.0
/home/chris/pitchfork/staging/ncurses-6.0/lib64/libpanel.so
/home/chris/pitchfork/staging/ncurses-6.0/lib64/libpanel.so.6
/home/chris/pitchfork/staging/ncurses-6.0/lib64/libpanel.so.6.0

**Comment by mhsieh** [comment]
this sounds like something easy to fix, I will do it after fixing currently broken build.

**Comment by mhsieh** [comment]
you can try again, with the latest version of pitchfork. Thanks!

**Comment by ccali930** [comment]
I tried again but got a similar error message:
tar zxf ncurses-6.0.tar.gz -C /home/chris/pitchfork/workspace
(cd /home/chris/pitchfork/workspace/ncurses-6.0 && CFLAGS="-fPIC -I/home/chris/pitchf                                                 ork/include" LDFLAGS="-L/home/chris/pitchfork/lib -Wl,-rpath,'\$\$ORIGIN/../lib' -sta                                                 tic-libgcc" CPP="gcc -E -P" ./configure --prefix=/home/chris/pitchfork --with-shared                                                  2>&1) \
        >& config.log || /home/chris/pitchfork/bin/diewith config.log
sleep 1
make -C /home/chris/pitchfork/workspace/ncurses-6.0 >& build.log || /home/chris/pitch                                                 fork/bin/diewith build.log
rm -rf /home/chris/pitchfork/staging/ncurses-6.0
make -C /home/chris/pitchfork/workspace/ncurses-6.0 prefix=/home/chris/pitchfork/stag                                                 ing/ncurses-6.0 install >& install.log || /home/chris/pitchfork/bin/diewith install.l                                                 og
test -d /home/chris/pitchfork/staging/ncurses-6.0/lib64 && ln -s lib64 /home/chris/pi                                                 tchfork/staging/ncurses-6.0/lib || true
ln -s libncurses.so /home/chris/pitchfork/staging/ncurses-6.0/lib/libcurses.so
cd /home/chris/pitchfork/staging/ncurses-6.0 && tar cf - * | tar xf - -C /home/chris/                                                 pitchfork
tar: lib: Cannot create symlink to ‘lib64’: File exists
tar: Exiting with failure status due to previous errors
Makefile:44: recipe for target '/home/chris/pitchfork/var/pkg/ncurses-6.0' failed
make[1]: *** [/home/chris/pitchfork/var/pkg/ncurses-6.0] Error 2
make[1]: Leaving directory '/home/chris/pitchfork/ports/thirdparty/ncurses'
Makefile:177: recipe for target 'ncurses' failed
make: *** [ncurses] Error 2
chris@TNRLserver:~/pitchfork>

**Comment by mhsieh** [comment]
that was my bad, I will fix it later today.

**Comment by mhsieh** [comment]
Dear Chris, How about now?

**Comment by ccali930** [comment]
It looks like the ncurses error is fixed, but now I get another error later on in the installation:

 BufferedHDF2DArray.shared.o -lpbdata -lhdf5 -lhdf5_cpp
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lhdf5
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lhdf5                           _cpp
collect2: error: ld returned 1 exit status
/home/chris/pitchfork/workspace/blasr_libcpp/hdf//../rules.mk:14: recipe for target 'libpbihd                           f.so' failed
make[3]: *** [libpbihdf.so] Error 1
make[3]: Leaving directory '/home/chris/pitchfork/workspace/blasr_libcpp/hdf'
makefile:21: recipe for target 'libpbihdf' failed
make[2]: *** [libpbihdf] Error 2
make[2]: Leaving directory '/home/chris/pitchfork/workspace/blasr_libcpp'
Makefile:34: recipe for target 'do-build' failed
make[1]: *** [do-build] Error 2
make[1]: Leaving directory '/home/chris/pitchfork/ports/pacbio/blasr_libcpp'
Makefile:339: recipe for target 'blasr_libcpp' failed
make: *** [blasr_libcpp] Error 2
chris@TNRLserver:~/pitchfork>

**Comment by mhsieh** [comment]
Dear Chris, do note that I have never used openSUSE before. I guess I would need to install one instance now.

**Comment by mhsieh** [comment]
Chris: Thanks for the wait, can you try again?

**Comment by ccali930** [comment]
Everything is installed and working properly now!! Thanks so much for all of your help!
