### ISSUE TITLE
no access to system binaries after terminating session with setup-env.sh

### ISSUE THREAD

**Issue by pawelosipowski** [PacificBiosciences/pitchfork#288]
It seems that after launching your setup-env.sh with bash I terminated terminal window and it modified system on start up. Details are here:http://unix.stackexchange.com/questions/309891/no-access-to-system-binaries-after-switching-off-terminal-with-bash-session-with. Can you help me?

**Comment by mhsieh** [comment]
if your bash is special, can you just do `source setup-env.sh` inside a session instead?

**Comment by pawelosipowski** [comment]
`$ source setup-env.sh
-bash: setup-env.sh: No such file or directory`

**Comment by mhsieh** [comment]
Hi Pawel, by referring "setup-env.sh" apparently I meant the full path to the setup-env.sh.

**Comment by pawelosipowski** [comment]
I cannot find path to setup-env.sh anymore. It seems I lost it.

**Comment by mhsieh** [comment]
it's at where you specified `PREFIX`, if you did not specify `PREFIX` variable when you built with pitchfork. it should be at your `pitchfork/deployment/` directory.

**Comment by pawelosipowski** [comment]
please look at my second post here to get an answer

**Comment by mhsieh** [comment]
I don't see your second post, but have you figured this out by yourself?

**Comment by pawelosipowski** [comment]
No I didn't. I just added the paths to PATH through .bashrc. That's far from perfect I guess... I'm reposting:

> $ source setup-env.sh -bash: setup-env.sh: No such file or directory
> and locate setup-env.sh gives me nothing. When I was compiling I used PREFIX=/tmp/pitchfork but now /tmp/ does not include pitchfork, if that is helpful somehow

**Comment by mhsieh** [comment]
your setup-env.sh is at `/storage3/long_read_assembly/soft/pitchfork/deployment/setup-env.sh`

**Comment by pawelosipowski** [comment]
This is not assigned to the latest build which you assisted [here](https://github.com/PacificBiosciences/pitchfork/issues/292). The thing is I cannot repeat that and I have disturbed default system environment after issue appeared, but it seems there will be no answer. I just patched my ~/.bashrc with system binaries in PATH what is workaround and than built `/storage3/long_read_assembly/soft/pitchfork/deployment/setup-env.sh`

**Comment by mhsieh** [comment]
What might have happened is that for many linux distribution, the /tmp directory are cleaned up everytime after an reboot. But that just was my guess.

**Comment by pawelosipowski** [comment]
cheers, closing it
