### ISSUE TITLE
HDF5 download

### ISSUE THREAD

**Issue by rrwick** [PacificBiosciences/pitchfork#289]
When using pitchfork to install BLASR, I ran into an error with HDF5. I think the problem is that pitchfork was looking here for the download:
`https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/src/hdf5-1.8.16.tar.gz`

But that link is dead (at least when I'm writing this). This one worked instead:
`https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/src/hdf5-1.8.16.tar.gz`

Perhaps HDF5 changed their website structure? I got around the issue by just downloading the file myself into the location where pitchfork wanted it, but perhaps `ports/thirdparty/hdf5/Makefile` needs to be updated with the new URL.

**Comment by mhsieh** [comment]
Thanks Ryan, I will close this after the automated build verifying the hotfix.

**Comment by mhsieh** [comment]
done

**Comment by kubu4** [comment]
It looks like they've reverted to the previous URL structure. Just tried installing legacy_blasr and got the following error message when running ```make blasr```:

```
make[1]: Leaving directory '/home/shared/pitchfork/ports/thirdparty/zlib'
make -C ports/thirdparty/hdf5 do-install
make[1]: Entering directory '/home/shared/pitchfork/ports/thirdparty/hdf5'
/home/shared/pitchfork/bin/pitchfork fetch --url https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/src/hdf5-1.8.16.tar.gz
fetching https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/src/hdf5-1.8.16.tar.gz
tar zxf hdf5-1.8.16.tar.gz -C /home/shared/pitchfork/workspace

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Makefile:23: recipe for target '/home/shared/pitchfork/workspace/hdf5-1.8.16' failed
make[1]: *** [/home/shared/pitchfork/workspace/hdf5-1.8.16] Error 2
make[1]: Leaving directory '/home/shared/pitchfork/ports/thirdparty/hdf5'
Makefile:211: recipe for target 'hdf5' failed
make: *** [hdf5] Error 2
```

The current working link is: https://hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.16/src/hdf5-1.8.16.tar.gz

And big thanks to @rrwick for the tip on fixing this! I downloaded the file and put it in the following location:

```pitchfork/ports/thirdparty/hdf5```
