### ISSUE TITLE
Issue with installing pbsmrtpipe (hdf5 problem)

### ISSUE THREAD

**Issue by rkizen** [PacificBiosciences/pitchfork#295]
I am having issues installing pbsmrtpipe using Pitchfork. From the errors it seems there is a problem with the hdf5 build. 

This is my OS version:
NAME="Scientific Linux"
VERSION="7.2 (Nitrogen)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Scientific Linux 7.2 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.2:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"
Scientific Linux release 7.2 (Nitrogen)
Scientific Linux release 7.2 (Nitrogen)
Scientific Linux release 7.2 (Nitrogen)

Here is a copy of the beginning of the build.log:

```
Making all in src
make[3]: Entering directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork-master/workspace/hdf5-1.8.16/src'
make  all-am
make[4]: Entering directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork-master/workspace/hdf5-1.8.16/src'
  CC       H5.lo
  CC       H5checksum.lo
H5checksum.c: In function 'H5_checksum_fletcher32':
H5checksum.c:112:1: warning: function might be candidate for attribute 'pure' if it is known to return normally [-Wsuggest-attribute=pure]
 H5_checksum_fletcher32(const void *_data, size_t _len)
 ^
H5checksum.c: In function 'H5_checksum_lookup3':
H5checksum.c:374:1: warning: function might be candidate for attribute 'pure' if it is known to return normally [-Wsuggest-attribute=pure]
 H5_checksum_lookup3(const void *key, size_t length, uint32_t initval)
 ^
H5checksum.c: In function 'H5_hash_string':
H5checksum.c:481:1: warning: function might be candidate for attribute 'pure' if it is known to return normally [-Wsuggest-attribute=pure]
 H5_hash_string(const char *str)
 ^
  CC       H5dbg.lo
H5dbg.c: In function 'H5_buffer_dump':
H5dbg.c:102:5: warning: cannot optimize loop, the loop counter may overflow [-Wunsafe-loop-optimizations]
     for(u = 0; u < buf_size; u += 16) {
     ^
  CC       H5system.lo
H5system.c: In function 'HDfprintf':
H5system.c:277:25: warning: format not a string literal, argument types not checked [-Wformat-nonliteral]
                         n = fprintf (stream, format_templ, x);
                         ^
H5system.c:280:25: warning: format not a string literal, argument types not checked [-Wformat-nonliteral]
                         n = fprintf (stream, format_templ, x);
                         ^
H5system.c:283:25: warning: format not a string literal, argument types not checked [-Wformat-nonliteral]
                         n = fprintf (stream, format_templ, x);
                         ^
H5system.c:286:25: warning: format not a string literal, argument types not checked [-Wformat-nonliteral]
                         n = fprintf (stream, format_templ, x);
                         ^
H5system.c:296:25: warning: format not a string literal, argument types not checked [-Wformat-nonliteral]
                         n = fprintf(stream, format_templ, x);
```

**Comment by mhsieh** [comment]
Hi Richard, the warnings do not seem to be serious, we probably need to scroll down to the place where the error started to happen.

Another possible way to do is to download https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/bin/linux-x86_64/hdf5-1.8.13-linux-x86_64-shared.tar.gz and extract the tar ball to a designated directory (for example: `tar zxf hdf5-1.8.13-linux-x86_64-shared.tar.gz -C /exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/`) and add one line in your settings.mk file like this:
```
HAVE_HDF5=/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/hdf5-1.8.13-linux-x86_64-shared
```

**Comment by mhsieh** [comment]
You can always refer to our travis-ci building script/settings at pitchfork/.travis.yml, pitchfork/mk/travis.mk pitchfork/bin/travisbuild.sh

**Comment by rkizen** [comment]
Hi Mengjuei,

I tried your suggestion but still have errors with the install. I also noticed that within the pitchfork-master folder settings.mk is a link as such:
settings.mk.original -> .git/settings.mk

However the path given does not exist. There is no settings.mk file within the .git folder. So what I did was rename the link to hide it and make a copy of the settings.mk.example file and named it settings.mk. I made the changes on the new settings.mk file. But if the link for the original file doesn't exist, what is the installer doing with it?

Here are the error outputs where it begins to have issues with hdf5:

make[4]: Leaving directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork-master/workspace/hdf5-1.8.16/tools/perform'
make[4]: Entering directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork-master/workspace/hdf5-1.8.16/tools'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork-master/workspace/hdf5-1.8.16/tools'
make[3]: Leaving directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork-master/workspace/hdf5-1.8.16/tools'
Making all in .
make[3]: Entering directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork-master/workspace/hdf5-1.8.16'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork-master/workspace/hdf5-1.8.16'
Making all in c++
make[3]: Entering directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork-master/workspace/hdf5-1.8.16/c++'
Making all in src
make[4]: Entering directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork-master/workspace/hdf5-1.8.16/c++/src'
  CXX      H5Exception.lo
In file included from H5Exception.cpp:19:0:
H5Exception.h:40:18: error: 'H5std_string' does not name a type
  Exception(const H5std_string& func_name, const H5std_string& message = DEFAULT_MSG);
                  ^
H5Exception.h:40:32: error: ISO C++ forbids declaration of 'func_name' with no type [-fpermissive]
  Exception(const H5std_string& func_name, const H5std_string& message = DEFAULT_MSG);
                                ^
H5Exception.h:40:49: error: 'H5std_string' does not name a type
  Exception(const H5std_string& func_name, const H5std_string& message = DEFAULT_MSG);
                                                 ^
H5Exception.h:40:73: error: ISO C++ forbids declaration of 'message' with no type [-fpermissive]
  Exception(const H5std_string& func_name, const H5std_string& message = DEFAULT_MSG);
                                                                         ^
H5Exception.h:44:2: error: 'H5std_string' does not name a type
  H5std_string getMajorString( hid_t err_major_id ) const;
  ^
H5Exception.h:48:2: error: 'H5std_string' does not name a type
  H5std_string getMinorString( hid_t err_minor_id ) const;
  ^
H5Exception.h:51:2: error: 'H5std_string' does not name a type
  H5std_string getDetailMsg() const;
  ^
H5Exception.h:53:2: error: 'H5std_string' does not name a type
  H5std_string getFuncName() const; // function name as a string object

**Comment by mhsieh** [comment]
First of all, at this moment we "envisioned" that people would directly overwrite the broken link. I have not figured out a better way to describe what we intended to do yet. :-)

I already gave you the tar ball so I imagine you can skip the hdf5 compilation if you extract it into your PREFIX.

**Comment by rkizen** [comment]
Ok so I moved the extracted tarball for hdf5 into the prefix and it seems like it may have worked but I am now getting this error:

Successfully installed pbcore-1.2.11
make[1]: Leaving directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork-master/ports/pacbio/pbcore'
make -j1 -C ports/python/pydot do-install
which: no dot in (/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork/2016-09-29/bin:/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork-master/bin:/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork/2016-09-29/bin:/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork-master/bin:/exports/applications//gridengine/2011.11p1_155/bin/linux-x64:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/exports/applications/apps/user-scripts/:/home/rkuo/.local/bin:/home/rkuo/bin)
make[1]: Entering directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork-master/ports/python/pydot'
Makefile:12: *** "unable to run dot, consider doing yum install graphviz".  Stop.
make[1]: Leaving directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/pitchfork-master/ports/python/pydot'
make: *** [pydot] Error 2


Any suggestions for this?

**Comment by mhsieh** [comment]
okay, let me see what I can do for you.

**Comment by rkizen** [comment]
Ok, I got graphviz installed and added it to my path and the the installation of smrtpipe worked!

**Comment by mhsieh** [comment]
I'm glad that I don't need to do anything before you figured it out. :-) I was starting to worry about the graphviz dependencies again and working on packing it for scientific linux 7 ...

**Comment by mhsieh** [comment]
fixed by user
