### ISSUE TITLE
IOError: pbalign no longer supports CMP.H5 Output in 3.0.

### ISSUE THREAD

**Issue by pawelosipowski** [PacificBiosciences/pitchfork#305]
please, could you provide older version of pbalign in pitchfork or give me work around to utilize quiver? piling up problems to make this through...

```
bash-4.1$ pbalign pb_2016.fofn pb_B10v2_12000.fasta pbalign_out.cmp.h5 --forQuiver --log-file pbalign.log --nproc 50
pbalign no longer supports CMP.H5 Output in 3.0.
Traceback (most recent call last):
  File "/home/clc03/pb_assembly_2/pitchfork/deployment/lib/python2.7/site-packages/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/clc03/pb_assembly_2/pitchfork/deployment/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 283, in args_runner
    return PBAlignRunner(args, output_dataset_type=output_dataset_type).start()
  File "/home/clc03/pb_assembly_2/pitchfork/deployment/lib/python2.7/site-packages/pbcore/util/ToolRunner.py", line 112, in start
    return self.run()
  File "/home/clc03/pb_assembly_2/pitchfork/deployment/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 236, in run
    self._makeSane(self.args, self.fileNames)
  File "/home/clc03/pb_assembly_2/pitchfork/deployment/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 153, in _makeSane
    raise IOError(errMsg)
IOError: pbalign no longer supports CMP.H5 Output in 3.0.

```

**Comment by mhsieh** [comment]
Hi Pawel,
    So remind me again, why can't we use smrtanalysis 2.3.x for your research?

**Comment by pawelosipowski** [comment]
I've never used smrtanalysis in my research. Always tried to install all the pipeline for quiver genome polishing alone and it worked well. I have no cluster but single workstation. When I read smrtanalysis introduction I couldn't actually get how can I make such simple stuff in my case... if you don't specifically ask about 2.3.x version.

**Comment by mhsieh** [comment]
for your pipeline using old quiver earlier than 3.0, my suggestion is that you install a smrtanalysis 2.3.0p5 in a local machine and transfer the installation to your software collections, you don't need to specify the cluster and running the daemon in order to use it.

If you like vagrant that kind of vm solution, see this https://github.com/mhsieh/SMRTAnalysis_2.3.0_install/blob/master/vagrant-u1404/Vagrantfile

**Comment by mhsieh** [comment]
After got the information from Vladimir, we can have more than one options for you. :-)

**Comment by mhsieh** [comment]
this is probably hacky, but if you feel like adventurous, add
```
pbalign_VERSION = 56782fe18849ba9014508fcaca6bfdfd29e8bd1b 
blasr_VERSION = 994e5fc10c2aee600ff83991d59a30213f89a3d2
```
into the `setting.mk` file.

**Comment by mhsieh** [comment]
Actually only specifying older version of blasr/pbalign might now work, since pbbam already updated since then.

**Comment by pawelosipowski** [comment]
Thanks, I'll get to it tomorrow and let you know! :)

**Comment by mhsieh** [comment]
I updated some more VERSION tag in settings.mk.

**Comment by pawelosipowski** [comment]
Unfortunatelly i get this:
[```
clc03@dell910 pitchfork]$ bash --init-file deployment/setup-env.sh 
bash-4.1$ blasr --version
blasr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by blasr)
blasr: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by blasr)
blasr: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/clc03/pb_assembly_2/pitchfork/deployment/lib/libpbihdf.so)
blasr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /home/clc03/pb_assembly_2/pitchfork/deployment/lib/libpbihdf.so)
blasr: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/clc03/pb_assembly_2/pitchfork/deployment/lib/libblasr.so)
blasr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /home/clc03/pb_assembly_2/pitchfork/deployment/lib/libblasr.so)
blasr: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/clc03/pb_assembly_2/pitchfork/deployment/lib/libpbdata.so)
blasr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /home/clc03/pb_assembly_2/pitchfork/deployment/lib/libpbdata.so)
blasr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /home/clc03/pb_assembly_2/pitchfork/deployment/lib/libpbbam.so)
blasr: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /home/clc03/pb_assembly_2/pitchfork/deployment/lib/libpbbam.so)
blasr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/clc03/pb_assembly_2/pitchfork/deployment/lib/libpbbam.so)
blasr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by /home/clc03/pb_assembly_2/pitchfork/deployment/lib/libpbbam.so)
blasr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by /home/clc03/pb_assembly_2/pitchfork/deployment/lib/libpbbam.so)
blasr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/clc03/pb_assembly_2/pitchfork/deployment/lib/libpbbam.so)
```

**Comment by mhsieh** [comment]
Did you clean up the build before doing it?

**Comment by pawelosipowski** [comment]
I did `clone` again

**Comment by mhsieh** [comment]
Possible problem I can imagine:
1. blasr you ran might be not from the the build
2. you might still need to enable the gcc (I meant toolchain) runtime. if you used some special way to enable a gcc 4.9.2, let me know.

We can schedule a net-meeting or some sort and see if I can control your screen a little bit to figure out what exactly the problem might be.

**Comment by pawelosipowski** [comment]
ad1 I just cloned pitchfork once more, inserted the lines above to settings.mk and ran `make blasr`
ad2 when I'm running your clean env. I get gcc 4.9.3, enabled in my system

**Comment by mhsieh** [comment]
another possibility is, that hdf5 lib might be prebuilt and reused through "HAVE_HDF5" option in settings.mk.

**Comment by mhsieh** [comment]
Can you share with us the version of the os you are using and the compiler version?

**Comment by mjhsieh** [comment]
Close this first, please file a new bug if you have another issue with the build.
