### ISSUE TITLE
checkCC missing case conditions 

### ISSUE THREAD

**Issue by rkizen** [PacificBiosciences/pitchfork#314]
Hello,

I noticed that if the gcc version does not meet the condtions in the case statement for the checkCC script, the script spits out this error:
"[ERROR] unexpected program error in $0"

This can be a bit confusing and I think it would be better to include a condition that states that the gcc version needs to be updated or something like that.

**Comment by mhsieh** [comment]
This was my bad, I will fix it.

**Comment by mhsieh** [comment]
works locally
