### ISSUE TITLE
Error in installing Pitchfork

### ISSUE THREAD

**Issue by bostanict** [PacificBiosciences/pitchfork#316]
Hi, I am trying to install Pitchfork and after I run:

make GenomicConsensus

this error shows up after all:

```
awk: symbol lookup error: /home/hbostan/soft/pitchfork/deployment/lib/libreadline.so.6: undefined symbol: UP
config.status: error: could not create Makefile.pre
Makefile:26: recipe for target '/home/hbostan/soft/pitchfork/workspace/Python-2.7.10/config.log' failed
make[1]: *** [/home/hbostan/soft/pitchfork/workspace/Python-2.7.10/config.log] Error 1
make[1]: Leaving directory '/home/hbostan/soft/pitchfork/ports/thirdparty/python'
Makefile:258: recipe for target 'python' failed
make: *** [python] Error 2
```

Thanks in advance

**Comment by mhsieh** [comment]
What version of OS are you using, if your default python is version greater than or equal to 2.7.3, write
```
HAVE_PYTHON = 
```
(You can keep right hand side empty and it will use python and skips the readline compilation.)

**Comment by bostanict** [comment]
Thanks for the reply,

I am using ubuntu 16.4 and I have both python 2.7 and 3.4
the one in path is 3.4 but is also the same for 2.7.

I have changed the HAVE_PYTHON to empty and then ran

it passed that error but now it sahows this:

```
gawk: symbol lookup error: /home/hbostan/soft/pitchfork/deployment/lib/libreadline.so.6: undefined symbol: UP
config.status: error: could not create src/libhdf5.settings
Makefile:26: recipe for target '/home/hbostan/soft/pitchfork/workspace/hdf5-1.8.16/config.log' failed
make[1]: *** [/home/hbostan/soft/pitchfork/workspace/hdf5-1.8.16/config.log] Error 1
make[1]: Leaving directory '/home/hbostan/soft/pitchfork/ports/thirdparty/hdf5'
Makefile:217: recipe for target 'hdf5' failed
make: *** [hdf5] Error 2

```

**Comment by mhsieh** [comment]
You will need to do `make _startover` to clean up the failed readline.

**Comment by mhsieh** [comment]
Ah... we have not tested system python3 of ubuntu16 yet. Let me go back to you and see if python3 works or not (likely not).

**Comment by mhsieh** [comment]
if your system python version (`python --version`) is 2.7.12, it should be fine if you also install libpython2.7-dev (by doing `apt-get install libpython2.7-dev`)

**Comment by bostanict** [comment]
OK, now I have all going until this error appears...


```
Scanning dependencies of target pbmerge
make[4]: Leaving directory '/home/hbostan/soft/pitchfork/workspace/pbbam/build'
make[4]: Entering directory '/home/hbostan/soft/pitchfork/workspace/pbbam/build'
[ 97%] Building CXX object tools/pbmerge/CMakeFiles/pbmerge.dir/__/common/OptionParser.cpp.o
[ 98%] Building CXX object tools/pbmerge/CMakeFiles/pbmerge.dir/src/main.cpp.o
[100%] Linking CXX executable ../../bin/pbmerge
make[4]: Leaving directory '/home/hbostan/soft/pitchfork/workspace/pbbam/build'
[100%] Built target pbmerge
make[3]: Leaving directory '/home/hbostan/soft/pitchfork/workspace/pbbam/build'
make[2]: Leaving directory '/home/hbostan/soft/pitchfork/workspace/pbbam/build'
cd /home/hbostan/soft/pitchfork/workspace/pbbam && tar cf - bin lib include | tar xf - -C /home/hbostan/soft/pitchfork/deployment
tar: bin: Cannot stat: No such file or directory
tar: lib: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
cd /home/hbostan/soft/pitchfork/workspace/pbbam && find bin lib include ! -type d > /home/hbostan/soft/pitchfork/deployment/var/pkg/pbbam
find: ‘bin’: No such file or directory
find: ‘lib’: No such file or directory
Makefile:43: recipe for target '/home/hbostan/soft/pitchfork/deployment/var/pkg/pbbam' failed
make[1]: *** [/home/hbostan/soft/pitchfork/deployment/var/pkg/pbbam] Error 1
make[1]: Leaving directory '/home/hbostan/soft/pitchfork/ports/pacbio/pbbam'
Makefile:367: recipe for target 'pbbam' failed
make: *** [pbbam] Error 2
```

**Comment by mhsieh** [comment]
please `git pull --rebase` and `rm deployment/var/pkg/pbbam`, I fixed that one several minutes ago.

**Comment by bostanict** [comment]
I ran git pull --rebase and then:

error: Cannot pull with rebase: You have unstaged changes.

**Comment by mhsieh** [comment]
Please use `git status` and see which file(s) did you modify by accident. :-)

**Comment by mhsieh** [comment]
If you did not intend to modify the file, use `git checkout <that file>` to revert the change.

**Comment by bostanict** [comment]
This is the output:
```

On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        typechange: settings.mk
        deleted:    settings.mk.example

no changes added to commit (use "git add" and/or "git commit -a")

```

**Comment by bostanict** [comment]
I just replaced the settings.mk.example with the symlink and changed the HAVE_PYTHON to nothing

**Comment by mhsieh** [comment]
```
mv settings.mk settings.mk.bostanict
git checkout settings.mk.example settings.mk
cat settings.mk.bostanict > settings.mk
```
to restore the example file and some minor adjustment :p

**Comment by bostanict** [comment]
OK, now when I run git pull rebase, it shows:


```
remote: Counting objects: 25, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 25 (delta 8), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (25/25), done.
From https://github.com/PacificBiosciences/pitchfork
   001d29b..f882c5b  master     -> origin/master
   170a95c..3a4891b  isoseq_sa3.2 -> origin/isoseq_sa3.2
First, rewinding head to replay your work on top of it...
Fast-forwarded master to f882c5b095963769487153d6b166a0110e889a04.

```

then? is it fixed?

**Comment by mhsieh** [comment]
Now you got the latest revision of pitchfork, please continue your make commands (make sure that var/pkg/pbbam is removed so it can do the right installation).

**Comment by bostanict** [comment]
should I git _startover again or just run the make GenomicConsensus?

the var/pkg/pbbam is removed but now that i run make GenomicConsensus, it shows error about swing. here is the tail of error:

```
`make[3]: Entering directory '/home/hbostan/soft/pitchfork/workspace/swig-3.0.8/CCache'
gcc -L/home/hbostan/soft/pitchfork/deployment/lib -fPIC -I/home/hbostan/soft/pitchfork/deployment/include -Wall -W -I.   -c -o ccache.o ccache.c
gcc -L/home/hbostan/soft/pitchfork/deployment/lib -fPIC -I/home/hbostan/soft/pitchfork/deployment/include -Wall -W -I.   -c -o mdfour.o mdfour.c
gcc -L/home/hbostan/soft/pitchfork/deployment/lib -fPIC -I/home/hbostan/soft/pitchfork/deployment/include -Wall -W -I.   -c -o hash.o hash.c
gcc -L/home/hbostan/soft/pitchfork/deployment/lib -fPIC -I/home/hbostan/soft/pitchfork/deployment/include -Wall -W -I.   -c -o execute.o execute.c
gcc -L/home/hbostan/soft/pitchfork/deployment/lib -fPIC -I/home/hbostan/soft/pitchfork/deployment/include -Wall -W -I.   -c -o util.o util.c
gcc -L/home/hbostan/soft/pitchfork/deployment/lib -fPIC -I/home/hbostan/soft/pitchfork/deployment/include -Wall -W -I.   -c -o args.o args.c
gcc -L/home/hbostan/soft/pitchfork/deployment/lib -fPIC -I/home/hbostan/soft/pitchfork/deployment/include -Wall -W -I.   -c -o stats.o stats.c
gcc -L/home/hbostan/soft/pitchfork/deployment/lib -fPIC -I/home/hbostan/soft/pitchfork/deployment/include -Wall -W -I.   -c -o cleanup.o cleanup.c
gcc -L/home/hbostan/soft/pitchfork/deployment/lib -fPIC -I/home/hbostan/soft/pitchfork/deployment/include -Wall -W -I.   -c -o snprintf.o snprintf.c
gcc -L/home/hbostan/soft/pitchfork/deployment/lib -fPIC -I/home/hbostan/soft/pitchfork/deployment/include -Wall -W -I.   -c -o unify.o unify.c
gcc -L/home/hbostan/soft/pitchfork/deployment/lib -fPIC -I/home/hbostan/soft/pitchfork/deployment/include -Wall -W -I. -L/home/hbostan/soft/pitchfork/deployment/lib -L/home/hbostan/soft/pitchfork/deployment/lib64 -Wl,-rpath,'\RIGIN/../lib',-rpath,'$ORIGIN/../lib' -static-libgcc -static-libstdc++ -o ccache-swig ccache.o mdfour.o hash.o execute.o util.o args.o stats.o cleanup.o snprintf.o unify.o -lz
make[3]: Leaving directory '/home/hbostan/soft/pitchfork/workspace/swig-3.0.8/CCache'
make[2]: Leaving directory '/home/hbostan/soft/pitchfork/workspace/swig-3.0.8'
Makefile:43: recipe for target 'do-build' failed
make[1]: *** [do-build] Error 1
make[1]: Leaving directory '/home/hbostan/soft/pitchfork/ports/thirdparty/swig'
Makefile:244: recipe for target 'swig' failed
make: *** [swig] Error 2

````

**Comment by bostanict** [comment]
Sorry, wait. Maybe I ran the command with not correct privileges. I am running with sudo now and is running. I will update here about the outcome.

**Comment by bostanict** [comment]
OK, I think it worked out.

So when I run these commands, here is the output:

```
hbostan@PHHI:~/soft/pitchfork$ bash --init-file /opt/pacbio/setup-env.sh
hbostan@PHHI:~/soft/pitchfork$ bin/pitchfork installed
iso8601-0.1.11
samtools-0.1.20
gtest-1.7.0
ConsensusCore
cmake-3.4.1
seqan
swig-3.0.8
h5py-2.4.0
pysam-0.9.0
xmlbuilder-1.0
pbcore
numpy-1.10.2
libressl-2.2.5
functools32-3.2.3-2
ccache-3.2.4
six-1.9.0
requests-2.7.0
ncurses-6.0
Cython-0.23.3
pbcommand
boost-1.60.0
OpenBLAS-0.2.18
jsonschema-2.4.0
avro-1.7.7
pbbam
GenomicConsensus
pip-7.1.2
hdf5-1.8.16
virtualenv-13.1.2
Python-2.7.10
readline-6.3
unanimity
zlib-1.2.8
tabulate-0.7.5
htslib
pbcopper

```

So is it complete?  The only think is that I want to run Quiver. To my understanding now if I run Quiver -h, it should work but it shows this message:

```
 Quiver --help
No command 'Quiver' found, did you mean:
 Command 'quiver' from package 'pbgenomicconsensus' (universe)
Quiver: command not found

```

anything missing?

**Comment by mjhsieh** [comment]
Hi Hamed, please don't use sudo to for pitchfork! What was the error message about the permission?

**Comment by mjhsieh** [comment]
Can you try open a new terminal window and type `which python`? I am starting to worry about everything.

**Comment by bostanict** [comment]
Hi @mjhsieh ,

sorry to worry you.

I installed it without sudo on another machine and it worked out. It gave all the same errors and I followed the same things you mentioned . I think the main issue is:

```
mv settings.mk settings.mk.bostanict
git checkout settings.mk.example settings.mk
cat settings.mk.bostanict > settings.mk
git pull --rebase
rm deployment/var/pkg/pbbam
```

so after this things go smooth.

I now run quiver -h and see the help. I am trying to install it on our main cluster and run polishing for our falcon assembled genome. I will get back to you if any question or issue.

Just to mention,  since at that time I ran everything by sudo, it told me can not create a folder sicne the whole folder was root privileged. But when ran it by sudo or in the other machine all by normal user, it went through and worked out.

Thanks a lot for the support and following the issue so precise and consistent.
Cheers

**Comment by mjhsieh** [comment]
Hi Hamed, can you take a look at ports/thirdparty/hdf5/build.log and see if there is anything wrong with the compilation.

By the way, `git pull` is not necessary if you don't have some specific revision you need to get that occurred after your `git clone` command.

**Comment by bostanict** [comment]
looking independently on both machines, i do not see any specific difference. Tomorrow I will grab the 2 files (one on the machine working and the other one not) and compare them to see the differences and let you know. 

Considering the git pull and the changes on the settings.mk, the symlink is red at the first place and when i run git it is not referring to the correct file. after running the checkout and cat ..., it becomes valid (referring to the file correctly) and the process goes through. Hope  I am clear. i will get back to you soon,

Thanks alot for all the support

**Comment by mjhsieh** [comment]
the broken symlink of settings.mk file is intentional just for the laziness of us doing the test :-D, don't worry about that. The trick I showed early on only reveals my habit (and some convention from Chris), not a big deal. I am currently trying to reproduce the problem from my vagrant instance (and I am recording a video about it.) and see if I can figure out something else.

**Comment by mjhsieh** [comment]
https://youtu.be/FbHyybZpEUE

**Comment by mjhsieh** [comment]
One another possibility is that you had different LD_LIBRARY_PATH variable prior entering the pitchfork environment. It probably can be resolved by using hdf5 from the system.

**Comment by bostanict** [comment]
Thanks @mjhsieh for the video and comments. I think they are very useful for all.

I also checked the different files this morning, they were the same. So I checked the LD_LIBRARY_PATH and one of them was pointing to an earlier version 4.9.... SO I fixed it to 5.2 and now is OK. Thanks

So following the topic, I am not sure if its still in the frame of topic but I am in fact going to use the quiver in PitchFork for the polishing. I need the bam file first to start quiver which should be in pbalign. is also pbalign also included in the Pitchfork and if yes how to call it?

Thanks in advacne

**Comment by mjhsieh** [comment]
You can continue to `make pbalign` and get a working pbalign inside the pitchfork environment (basically just a bash session with setting from setup-env.sh).

**Comment by bostanict** [comment]
So by default the packages are not installed after the main make GenomicConsensus, we need to make each one right?

I am also running into another trouble for the Quiver. I ma not sure if it is due to the input format or some of my packages have issues, 


I am just trying to test. I used h5 file, gave error. Tried sam output of pbalign, again error. Coverted the sam using samtools to bam, now the error is different 

here is the error:

```
[ERROR] 'BASECALLERVERSION'
Traceback (most recent call last):
  File "/home3/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home3/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/GenomicConsensus/main.py", line 381, in args_runner
    return tr.main()
  File "/home3/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/GenomicConsensus/main.py", line 297, in main
    with AlignmentSet(options.inputFilename) as peekFile:
  File "/home3/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2592, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/home3/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1917, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/home3/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 471, in __init__
    self.updateCounts()
  File "/home3/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2433, in updateCounts
    self.assertIndexed()
  File "/home3/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2234, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/home3/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1874, in _assertIndexed
    self._openFiles()
  File "/home3/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1994, in _openFiles
    resource = IndexedBamReader(location)
  File "/home3/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 385, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/home3/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 199, in __init__
    self._loadReadGroupInfo()
  File "/home3/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 112, in _loadReadGroupInfo
    basecallerVersion = ".".join(ds["BASECALLERVERSION"].split(".")[0:2])
KeyError: 'BASECALLERVERSION'

```

Thanks

**Comment by mjhsieh** [comment]
Latest version of pbalign no longer support sam output and quiver/arrow doesn't support bam without pacbio headers.

So lets talk about the HDF5 error. Your environment might have some other interference that prevents local build from source. My suggestion is to install libhdf5-serial-dev and use this line in your settings.mk.
```
HAVE_HDF5 = /usr
```
(Also make sure that you uninstall hdf5 and h5py from the pitchfork deployment and the workspace of hdf5 need to be removed.)

**Comment by bostanict** [comment]
Hi,

I am sorry for my late reply. We had some hardware issues here.

>Latest version of pbalign no longer support sam output and quiver/arrow doesn't support bam without pacbio headers.

so what is the solution. So should I run the pbalign to produce bam? will this bam file be accepted for quiver?  We have RS II data. How can we run quiver for a genome assembly using this data? 


> So lets talk about the HDF5 error. Your environment might have some other interference that prevents local build from source. My suggestion is to install libhdf5-serial-dev and use this line in your settings.mk.

I had to install pitchfork locally and also the gcc version was old so we had to install that locally too. my interface points now to the correct version. Anyway I can not remove anything on this machine. Does it make sense or I am not understanding correctly what you mean?

Thanks alot~

**Comment by mhsieh** [comment]
with regard to hdf5, didn't you mention that you were using ubuntu 16? I fail to accept that system gcc5 is too old.

**Comment by bostanict** [comment]
I am sorry @mhsieh  if I confused you. I have 2 servers

1 is the old one (big cluster unfortunately that probably we need to run quiver on that) and one ubuntu 16 (big but not as powerful as first one). Although in both cases the error is the same (provided above) and I do not have root privileges.

anyway since I am no expert, if you tell me how to proceed I will do. I can not install libhdf5-serial-dev at the moment. Is there any alternative that I can do it locally.

Just to mention, I typed python and then import h5py as the video toturial. It gives me no error. When ir un quiver -h also it works but when providing inputs etc, it fails

thanks and sorry again for the confusion.

**Comment by bostanict** [comment]
Hi,

I did as you said on my ubuntu 16:

```
sudo apt-get install  libhdf5-serial-dev 

rm deployment/var/pkg/h5py-2.4.0
rm deployment/var/pkg/hdf5-1.8.16

rm workspace/hdf5-1.8.16/
```

then I changed this:

```
HAVE_HDF5 = /usr
```


and 

`made GenomicConsensus`

error:


```
'BASECALLERVERSION'
Traceback (most recent call last):
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/GenomicConsensus/main.py", line 381, in args_runner
    return tr.main()
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/GenomicConsensus/main.py", line 297, in main
    with AlignmentSet(options.inputFilename) as peekFile:
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2592, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1917, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 471, in __init__
    self.updateCounts()
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2433, in updateCounts
    self.assertIndexed()
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2234, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1874, in _assertIndexed
    self._openFiles()
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1994, in _openFiles
    resource = IndexedBamReader(location)
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 385, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 199, in __init__
    self._loadReadGroupInfo()
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 112, in _loadReadGroupInfo
    basecallerVersion = ".".join(ds["BASECALLERVERSION"].split(".")[0:2])
KeyError: 'BASECALLERVERSION'
[ERROR] 'BASECALLERVERSION'
Traceback (most recent call last):
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/GenomicConsensus/main.py", line 381, in args_runner
    return tr.main()
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/GenomicConsensus/main.py", line 297, in main
    with AlignmentSet(options.inputFilename) as peekFile:
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2592, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1917, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 471, in __init__
    self.updateCounts()
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2433, in updateCounts
    self.assertIndexed()
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2234, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1874, in _assertIndexed
    self._openFiles()
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1994, in _openFiles
    resource = IndexedBamReader(location)
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 385, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 199, in __init__
    self._loadReadGroupInfo()
  File "/home/hbostan/soft/pitchfork/deployment/local/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 112, in _loadReadGroupInfo
    basecallerVersion = ".".join(ds["BASECALLERVERSION"].split(".")[0:2])
KeyError: 'BASECALLERVERSION'

```

I should also mention that the bam file was created using the pbalign in pitchfork package

thanks in advance

**Comment by mhsieh** [comment]
After asking around, If the bam subread is recreated from fasta, this should be the right failure.

**Comment by bostanict** [comment]
I am sorry @mhsieh but your answer is not clear to me. Can you tell me what you mean. OK I assume that the failure is expected how can we fix it. I am sorry if I missed some points.

I used the pbalign to map the subreads from on the genome assembly we made. The output is bam as I specified. So if I should not use the fasta file, can you tell me how to run and fix the issue. 

Thanks alot

**Comment by mhsieh** [comment]
Hi Hamed, how did you generate the input bam? for the pbalign?

**Comment by bostanict** [comment]
This is the command I used after entring thie pitchfork environment:

```
pbalign data/m160716_091829_42133_c101002472550000001823228709161675_s1_p0.1.subreads.fasta 2-asm-falcon/p_ctg.fa quiver-wrk/mapping/test.bam
```

**Comment by mhsieh** [comment]
Dear Hamed, You need to convert the data/m160716_091829_42133_c101002472550000001823228709161675_s1_p0.1.bax.h5 file into subread.bam files.

**Comment by bostanict** [comment]
Thanks for the hint :)

I am doing it now. I will get back to you after conversion and running. Hopefully no error or mistake any more and it will get through.

One more question, is it better to convert each h5 independently to bam for quiver or it is better to combine all in one bam file? any experience on this?

thanks

**Comment by mhsieh** [comment]
You can always combine bam files virtually in subreadset.xml, does this help?

**Comment by bostanict** [comment]
Thanks @mhsieh , Yes I also heard in the pacbio meeting that this is possible in the xml file, thanks for the hint but mainly I mean if it will have any significant effect on the computational power to quiver if we have all in one bam or if we have in multiple files. parallelization wise...

**Comment by mhsieh** [comment]
It's trickier in parallelism. You will need to learn a little bit from "dataset split --help" and http://pacificbiosciences.github.io/pbcoretools/pbcoretools.html

**Comment by mhsieh** [comment]
Overall a pbsmrtpipe resequencing job should give you the better polish result/better performance right off the bat.

**Comment by pb-cdunn** [comment]
>  I also heard in the pacbio meeting

:smile:

@bostanict, Which meeting? Have we meet?

**Comment by bostanict** [comment]
>Overall a pbsmrtpipe resequencing job should give you the better polish result/better performance right off the bat.

thanks @mhsieh  but can you give me a hint why? is the algorithm different? or there are post processings involved?

>Which meeting? Have we meet?

I think we met. We were present in the East Cost meetings. The one in Maryland and also the developers one. We were from NC State. :)

**Comment by mjhsieh** [comment]
The stock parameters works in many cases, and you normally don't need to worry about parallelism too much.

**Comment by bostanict** [comment]
Thanks a lot. We had some issues with the smrt portal and at the meantime of using pitchfork that I quite like it a lot we are also trying to fix the smrtportal to make it run.

after the comments and tips in this thread, I think the arrow is working. I will wait for the outcome and see how it goes.

I have another quick question and I believe is the last one. For a diploid and highly hetreozygous genome, in practice and based on any experience you might have is quiver better or arrow?

Cheers

**Comment by mjhsieh** [comment]
With regard to the polishing question, you probably should open an issue in the genomicconsensus project . :p

**Comment by mhsieh** [comment]
I am going to close this as "resolved"

**Comment by josecarballo87** [comment]
Hello, I have the same problem with arrow [ERROR] 'BASECALLERVERSION', could you explain me how you fixed. I also aligned with pbalign before try to run arrow. Can you send me your command?
Thank in advance
