### ISSUE TITLE
CC check failed

### ISSUE THREAD

**Issue by fklayer** [PacificBiosciences/pitchfork#319]
Hi there,

I am trying to use pitchfork to install blasr, but pitchfork reported error from the very first step, when I use 
make init, it reported this error message:

make -f mk/init.mk init
make[1]: Entering directory `/home/fengk/software/pitchfork'
/home/fengk/software/pitchfork/bin/checkSystem
/home/fengk/software/pitchfork/bin/checkCC gcc
[ERROR] gcc version needs to be newer than or equal to 4.9
make[1]: *** [sanity] Error 1
make[1]: Leaving directory `/home/fengk/software/pitchfork'
/home/fengk/software/pitchfork/bin/checkSystem
/home/fengk/software/pitchfork/bin/checkCC gcc
[ERROR] gcc version needs to be newer than or equal to 4.9
make: *** [sanity] Error 1

it seems that my gcc version is lower than 4.9, after I installed gcc  5.3.0 in my account, and changed the config.mk file to set correct gcc path point to gcc 5.3.0, make init reported this:

make -f mk/init.mk init
make[1]: Entering directory `/home/fengk/software/pitchfork'
/home/fengk/software/pitchfork/bin/checkSystem
/home/fengk/software/pitchfork/bin/checkCC /opt/software/gcc-5.3/bin/gcc
[ERROR] unrecognized CC, please send us info if you think this CC is valid
make[1]: *** [sanity] Error 1
make[1]: Leaving directory `/home/fengk/software/pitchfork'
/home/fengk/software/pitchfork/bin/checkSystem
/home/fengk/software/pitchfork/bin/checkCC /opt/software/gcc-5.3/bin/gcc
[ERROR] unrecognized CC, please send us info if you think this CC is valid
make: *** [sanity] Error 1

Can you guys fix this problem?

Thanks,

Kai

**Comment by mjhsieh** [comment]
this might be a bug, I will take a look.

**Comment by mjhsieh** [comment]
Can you send me the output of your `gcc -dumpversion` command for both 4.9 and 5.3 version of gcc?

**Comment by mjhsieh** [comment]
Don't modify the config.mk, just prepend /opt/software/gcc-5.3/bin/ to your PATH.

The right place to specify the compiler is to add line into your settings.mk.
```CC = gcc-blah```

Now here comes the bug, I didn't do pattern match on the full path. This will be fix later. And I am still curious about what happen to your gcc4.9 -dumpversion output.

**Comment by fklayer** [comment]
Here is the gcc dumpversion for gcc4.9:

$ ./gcc -dumpversion
4.9.2

this for gcc5.3:

$ /opt/software/gcc-5.3/bin/gcc -dumpversion
5.3.0

the output seems quite ok to me ....

**Comment by fklayer** [comment]
After add gcc to my PATH and modify the settings.mk.

make -f mk/init.mk init
make[1]: Entering directory `/home/fengk/software/pitchfork'
/home/fengk/software/pitchfork/bin/checkSystem
/home/fengk/software/pitchfork/bin/checkCC /opt/software/gcc-5.3/bin/gcc
[ERROR] unrecognized CC, please send us info if you think this CC is valid
make[1]: *** [sanity] Error 1
make[1]: Leaving directory `/home/fengk/software/pitchfork'
/home/fengk/software/pitchfork/bin/checkSystem
/home/fengk/software/pitchfork/bin/checkCC /opt/software/gcc-5.3/bin/gcc
[ERROR] unrecognized CC, please send us info if you think this CC is valid
make: *** [sanity] Error 1

same error occured

**Comment by mjhsieh** [comment]
currently you can't use full path, you don't need to define CC in settings.mk if you are using gcc.

**Comment by mjhsieh** [comment]
Basically don't touch config.mk.

**Comment by fklayer** [comment]
I've returned config.mk to its original status, and delete CC line in settings.mk and add gcc bin to my PATH, still returns this error message:

$ make init
make -f mk/init.mk init
make[1]: Entering directory `/home/fengk/software/pitchfork'
/home/fengk/software/pitchfork/bin/checkSystem
/home/fengk/software/pitchfork/bin/checkCC gcc
[ERROR] gcc version needs to be newer than or equal to 4.9
make[1]: *** [sanity] Error 1
make[1]: Leaving directory `/home/fengk/software/pitchfork'
/home/fengk/software/pitchfork/bin/checkSystem
/home/fengk/software/pitchfork/bin/checkCC gcc
[ERROR] gcc version needs to be newer than or equal to 4.9
make: *** [sanity] Error 1

**Comment by mjhsieh** [comment]
Very interesting, what OS are you using?

**Comment by fklayer** [comment]
my system is centos 6.5, I could install blasr on my system but it seems that you guys removed the sam or bam support in blasr 5.3,  since I am going to use quiver to polish my assembly, can you guys provide a blasr version with sam or bam support instead of using pitchfork?

**Comment by mjhsieh** [comment]
The short answer is a no. Can you please use the smrtanalysis 2.3.0p5 instead if you don't want to compile it yourself?

**Comment by mjhsieh** [comment]
Centos6 is one of our most tested systems using pitchfork, I can't speculate why it doesn't work for you. Can you share with us the output of this command?

```
printf '4.9\n%s\n' `gcc -dumpversion` | sort -t. -k1,2
```

**Comment by fklayer** [comment]
$ printf '4.9\n%s\n' `gcc -dumpversion` | sort -t. -k1,2
4.4.7
4.9

**Comment by mjhsieh** [comment]
so you are still using system gcc, would you mind sharing the output of 
```echo $PATH```
?

**Comment by fklayer** [comment]
echo $PATH

/usr/local/maui/sbin:/usr/local/maui/bin:/opt/tsce/share/bin:/opt/tsce/share/sbin:/opt/tsce/share/jdk1.6.0_10/bin:/opt/tsce/share/jdk1.6.0_10/jre/bin:/usr/lib64/qt-3.3/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/opt/intel//impi/5.0.2.044/intel64/bin:/opt/intel/composer_xe_2015.1.133/bin/intel64:/opt/intel/composer_xe_2015.1.133/debugger/gdb/intel64_mic/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin:.:/home/fengk/software/blasr_install/blasr:/home/fengk/software/blasr_install/blasr/utils:/opt/software/gcc-5.3/bin/:/home/fengk/bin

**Comment by mjhsieh** [comment]
/opt/software/gcc-5.3/bin needs to be in front of /usr/bin, or you won't be able to have a working gcc5.3 (well, perhaps you still get a sorta working one.)

**Comment by fklayer** [comment]
Well, thanks for your advice, I after I change the gcc/bin PATH in front of ./usr/bin, make init actually works, now I am trying to install blasr, and I will be updating the installing status to you guys. anyway, Thanks mj.

**Comment by fklayer** [comment]
It worked!

Thanks mj, I think you should close this issue now.
