### ISSUE TITLE
Problem with samtools 1.3.1 on Scientific Linux release 6

### ISSUE THREAD

**Issue by a-velt** [PacificBiosciences/pitchfork#333]
Dear developers,

I have a problem when trying to install blasr via pitchfork.

My commands : 

git clone https://github.com/PacificBiosciences/pitchfork.git
cd pitchfork/
make PREFIX=/my_folder blasr

I get the error:

> make -C ports/thirdparty/ncurses do-install
make[1]: Entering directory `/cm/shared/apps/pitchfork/ports/thirdparty/ncurses'
/cm/shared/apps/pitchfork/bin/pitchfork fetch --url ftp://ftp.gnu.org/gnu/ncurses/ncurses-6.0.tar.gz
fetching ftp://ftp.gnu.org/gnu/ncurses/ncurses-6.0.tar.gz
{'url': 'ftp://ftp.gnu.org/gnu/ncurses/ncurses-6.0.tar.gz', 'subcommand': 'fetch'}
Traceback (most recent call last):
  File "/cm/shared/apps/pitchfork/bin/pitchfork", line 317, in <module>
    sys.exit(main())
  File "/cm/shared/apps/pitchfork/bin/pitchfork", line 310, in main
    pitchfork(pargs)
  File "/cm/shared/apps/pitchfork/bin/pitchfork", line 296, in pitchfork
    _out, _exit, _err = backticks('curl -L -O %s' % _url, checked=True)
  File "/cm/shared/apps/pitchfork/bin/pitchfork", line 55, in backticks
    errCode, cmd, errorMessage))
Exception: 28 <- `curl -L -O ftp://ftp.gnu.org/gnu/ncurses/ncurses-6.0.tar.gz`
          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (28) Timeout was reached
make[1]: *** [ncurses-6.0.tar.gz] Error 1
make[1]: Leaving directory `/cm/shared/apps/pitchfork/ports/thirdparty/ncurses'
make: *** [ncurses] Error 2

So, I put the archive ncurses-6.0.tar.gz directly in the folder /cm/shared/apps/pitchfork/ports/thirdparty/ncurses and I relaunch : 

make PREFIX=/my_folder blasr

When the command "gcc -g -Wall -O2 -fPIC -I/cm/shared/apps/pitchfork/blasr/include -I. -I/cm/shared/apps/pitchfork/workspace/samtools-1.3.1/htslib-1.3.1  -c -o bam_tview_curses.o bam_tview_curses.c" is launched, I get the errors : 

> bam_tview_curses.c:46:5: error: unknown type name ‘WINDOW’
     WINDOW *wgoto, *whelp;
     ^
bam_tview_curses.c: In function ‘curses_destroy’:
bam_tview_curses.c:56:5: warning: implicit declaration of function ‘delwin’ [-Wimplicit-function-declaration]
     delwin(tv->wgoto); delwin(tv->whelp);
     ^
bam_tview_curses.c:57:5: warning: implicit declaration of function ‘endwin’ [-Wimplicit-function-declaration]
     endwin();
     ^
bam_tview_curses.c: In function ‘curses_mvprintw’:
bam_tview_curses.c:82:5: warning: implicit declaration of function ‘mvprintw’ [-Wimplicit-function-declaration]
     mvprintw(y,x,str);
     ^
bam_tview_curses.c: In function ‘curses_mvaddch’:
bam_tview_curses.c:88:5: warning: implicit declaration of function ‘mvaddch’ [-Wimplicit-function-declaration]
     mvaddch(y,x,ch);
     ^
bam_tview_curses.c: In function ‘curses_attron’:
bam_tview_curses.c:93:5: warning: implicit declaration of function ‘attron’ [-Wimplicit-function-declaration]
     attron(flag);
     ^
bam_tview_curses.c: In function ‘curses_attroff’:
bam_tview_curses.c:97:5: warning: implicit declaration of function ‘attroff’ [-Wimplicit-function-declaration]
     attroff(flag);
     ^
bam_tview_curses.c: In function ‘curses_clear’:
bam_tview_curses.c:101:5: warning: implicit declaration of function ‘clear’ [-Wimplicit-function-declaration]
     clear();
     ^
bam_tview_curses.c: In function ‘curses_init_colors’:
bam_tview_curses.c:107:9: warning: implicit declaration of function ‘init_pair’ [-Wimplicit-function-declaration]
         init_pair(1, COLOR_WHITE, COLOR_BLUE);
         ^
bam_tview_curses.c:107:22: error: ‘COLOR_WHITE’ undeclared (first use in this function)
         init_pair(1, COLOR_WHITE, COLOR_BLUE);
                      ^
bam_tview_curses.c:107:22: note: each undeclared identifier is reported only once for each function it appears in
bam_tview_curses.c:107:35: error: ‘COLOR_BLUE’ undeclared (first use in this function)
         init_pair(1, COLOR_WHITE, COLOR_BLUE);
                                   ^
bam_tview_curses.c:108:22: error: ‘COLOR_BLACK’ undeclared (first use in this function)
         init_pair(2, COLOR_BLACK, COLOR_GREEN);
                      ^
bam_tview_curses.c:108:35: error: ‘COLOR_GREEN’ undeclared (first use in this function)
         init_pair(2, COLOR_BLACK, COLOR_GREEN);
                                   ^
bam_tview_curses.c:109:35: error: ‘COLOR_YELLOW’ undeclared (first use in this function)
         init_pair(3, COLOR_BLACK, COLOR_YELLOW);
                                   ^
bam_tview_curses.c:112:35: error: ‘COLOR_CYAN’ undeclared (first use in this function)
         init_pair(6, COLOR_BLACK, COLOR_CYAN);
                                   ^
bam_tview_curses.c:113:35: error: ‘COLOR_MAGENTA’ undeclared (first use in this function)
         init_pair(7, COLOR_WHITE, COLOR_MAGENTA);
                                   ^
bam_tview_curses.c:114:35: error: ‘COLOR_RED’ undeclared (first use in this function)
         init_pair(8, COLOR_WHITE, COLOR_RED);
                                   ^
bam_tview_curses.c: In function ‘curses_colorpair’:
bam_tview_curses.c:133:5: warning: implicit declaration of function ‘COLOR_PAIR’ [-Wimplicit-function-declaration]
     return COLOR_PAIR(flag);
     ^
bam_tview_curses.c: In function ‘tv_win_goto’:
bam_tview_curses.c:148:5: warning: implicit declaration of function ‘wborder’ [-Wimplicit-function-declaration]
     wborder(tv->wgoto, '|', '|', '-', '-', '+', '+', '+', '+');
     ^
bam_tview_curses.c:149:5: warning: implicit declaration of function ‘mvwprintw’ [-Wimplicit-function-declaration]
     mvwprintw(tv->wgoto, 1, 2, "Goto: ");
     ^
bam_tview_curses.c:152:9: warning: implicit declaration of function ‘wgetch’ [-Wimplicit-function-declaration]
         int c = wgetch(tv->wgoto);
         ^
bam_tview_curses.c:153:9: warning: implicit declaration of function ‘wrefresh’ [-Wimplicit-function-declaration]
         wrefresh(tv->wgoto);
         ^
bam_tview_curses.c:154:18: error: ‘KEY_BACKSPACE’ undeclared (first use in this function)
         if (c == KEY_BACKSPACE || c == '\010' || c == '\177') {
                  ^
bam_tview_curses.c:156:25: error: ‘KEY_ENTER’ undeclared (first use in this function)
         } else if (c == KEY_ENTER || c == '\012' || c == '\015') {
                         ^
bam_tview_curses.c:191:9: warning: implicit declaration of function ‘mvwaddch’ [-Wimplicit-function-declaration]
         for (i = 0; i < TV_MAX_GOTO; ++i) mvwaddch(tv->wgoto, 1, 8 + i, ' ');
         ^
bam_tview_curses.c: In function ‘tv_win_help’:
bam_tview_curses.c:203:5: error: unknown type name ‘WINDOW’
     WINDOW *win = tv->whelp;
     ^
bam_tview_curses.c: In function ‘curses_underline’:
bam_tview_curses.c:239:12: error: ‘A_UNDERLINE’ undeclared (first use in this function)
     return A_UNDERLINE;
            ^
bam_tview_curses.c: In function ‘curses_loop’:
bam_tview_curses.c:248:9: warning: implicit declaration of function ‘getch’ [-Wimplicit-function-declaration]
         int c = getch();
         ^
bam_tview_curses.c:263:18: error: ‘KEY_LEFT’ undeclared (first use in this function)
             case KEY_LEFT:
                  ^
bam_tview_curses.c:265:18: error: ‘KEY_RIGHT’ undeclared (first use in this function)
             case KEY_RIGHT:
                  ^
bam_tview_curses.c:267:18: error: ‘KEY_SLEFT’ undeclared (first use in this function)
             case KEY_SLEFT:
                  ^
bam_tview_curses.c:269:18: error: ‘KEY_SRIGHT’ undeclared (first use in this function)
             case KEY_SRIGHT:
                  ^
bam_tview_curses.c:278:18: error: ‘KEY_UP’ undeclared (first use in this function)
             case KEY_UP:
                  ^
bam_tview_curses.c:280:18: error: ‘KEY_DOWN’ undeclared (first use in this function)
             case KEY_DOWN:
                  ^
bam_tview_curses.c:282:18: error: ‘KEY_BACKSPACE’ undeclared (first use in this function)
             case KEY_BACKSPACE:
                  ^
bam_tview_curses.c:284:18: error: ‘KEY_RESIZE’ undeclared (first use in this function)
             case KEY_RESIZE: getmaxyx(stdscr, tv->mrow, tv->mcol); break;
                  ^
bam_tview_curses.c:284:13: warning: implicit declaration of function ‘getmaxyx’ [-Wimplicit-function-declaration]
             case KEY_RESIZE: getmaxyx(stdscr, tv->mrow, tv->mcol); break;
             ^
bam_tview_curses.c:284:39: error: ‘stdscr’ undeclared (first use in this function)
             case KEY_RESIZE: getmaxyx(stdscr, tv->mrow, tv->mcol); break;
                                       ^
bam_tview_curses.c: In function ‘curses_tv_init’:
bam_tview_curses.c:324:5: warning: implicit declaration of function ‘initscr’ [-Wimplicit-function-declaration]
     initscr();
     ^
bam_tview_curses.c:325:5: warning: implicit declaration of function ‘keypad’ [-Wimplicit-function-declaration]
     keypad(stdscr, TRUE);
     ^
bam_tview_curses.c:325:12: error: ‘stdscr’ undeclared (first use in this function)
     keypad(stdscr, TRUE);
            ^
bam_tview_curses.c:325:20: error: ‘TRUE’ undeclared (first use in this function)
     keypad(stdscr, TRUE);
                    ^
bam_tview_curses.c:327:5: warning: implicit declaration of function ‘noecho’ [-Wimplicit-function-declaration]
     noecho();
     ^
bam_tview_curses.c:328:5: warning: implicit declaration of function ‘cbreak’ [-Wimplicit-function-declaration]
     cbreak();
     ^
bam_tview_curses.c:331:5: warning: implicit declaration of function ‘newwin’ [-Wimplicit-function-declaration]
     tv->wgoto = newwin(3, TV_MAX_GOTO + 10, 10, 5);
     ^
bam_tview_curses.c:331:15: warning: assignment makes pointer from integer without a cast
     tv->wgoto = newwin(3, TV_MAX_GOTO + 10, 10, 5);
               ^
bam_tview_curses.c:332:15: warning: assignment makes pointer from integer without a cast
     tv->whelp = newwin(30, 40, 5, 5);
               ^
bam_tview_curses.c:334:5: warning: implicit declaration of function ‘start_color’ [-Wimplicit-function-declaration]
     start_color();
     ^
bam_tview_curses.c: In function ‘curses_underline’:
bam_tview_curses.c:240:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
make[2]: *** [bam_tview_curses.o] Error 1
make[2]: Leaving directory `/cm/shared/apps/pitchfork/workspace/samtools-1.3.1'
make[1]: *** [/cm/shared/apps/pitchfork/workspace/samtools-1.3.1/samtools] Error 1
make[1]: Leaving directory `/cm/shared/apps/pitchfork/ports/thirdparty/samtools'
make: *** [samtools] Error 2

If I go to the folder : 

cd /pitchfork/ports/thirdparty/samtools

There is the archive "samtools-1.3.1.tar.bz2" and I don't know where is the error. Because "/pitchfork/workspace/samtools-1.3.1/htslib-1.3.1" exists.

EDIT : 

In the /pitchfork/ports/thirdparty/samtools folder, in the config.log file, there is a warning with ncurses, so the problem seems to come from ncurses but I don't know how correcting that.

>  checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for NcursesW wide-character library... yes
checking for working ncursesw/curses.h... no
checking for working ncursesw.h... no
checking for working ncurses.h... no
configure: WARNING: could not find a working ncursesw/curses.h, ncursesw.h or ncurses.h
checking for zlib.h... yes
checking for inflate in -lz... yes
configure: creating ./config.status
config.status: creating config.mk
config.status: creating config.h

Have you a solution ?

Best,
Amandine

**Comment by mhsieh** [comment]
Hi, can you tell us which linux distribution / OS are you using?

**Comment by a-velt** [comment]
Thank you for your rapid answer.

cat /proc/version
> Linux version 2.6.32-504.8.1.el6.x86_64 (mockbuild@sl6-kojislave01.fnal.gov) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) ) #1 SMP Tue Jan 27 13:39:10 CST 2015

So, initially, I have gcc --version : 
> gcc (GCC) 4.8.4

And I can use a more recent version of GCC like that : 
scl enable devtoolset-3 bash

And then I have : 
gcc --version
> gcc (GCC) 4.9.1 20140922 (Red Hat 4.9.1-10)

(This is the GCC version I used to try to compile blasr)

Best,
Amandine

**Comment by a-velt** [comment]
Just for notification.

In the file : /pitchfork/ports/thirdparty/ncurses/Makefile, I change "pitchfork fetch url" command, which use Curl, by wget and the upload and installation of ncurses worked successfully. So the first error came from curl command (due to my configuration, I think).

So I re-launch : 
> git clone https://github.com/PacificBiosciences/pitchfork.git
cd pitchfork/

After adding the wget command, I re-launch the "make PREFIX=/my_folder blasr" and I get directly the last error, with samtools (so there is no longer problem with ncurses installation step)

In the /pitchfork/ports/thirdparty/ncurses/install.log file, there is no error, but in /pitchfork/ports/thirdparty/samtools/config.log, I have always the warning "could not find a working ncursesw/curses.h, ncursesw.h or ncurses.h"

Hope this help ...

Best,
Amandine

**Comment by mhsieh** [comment]
First of all, I think the curl error was just temporary. and as to the tinfo issue with SciLinuxR6, I will test the issue on my vms and see if we can provide a more general solution.

**Comment by mhsieh** [comment]
I was not able to reproduce this in my own SL box. my configuration:
```
[vagrant@localhost ~]$ lsb_release -d
Description:	Scientific Linux release 6.6 (Carbon)
[vagrant@localhost ~]$ scl enable devtoolset-3 bash
[vagrant@localhost ~]$ gcc -dumpversion
4.9.1
[vagrant@localhost ~]$ rpm -qa|grep ncurses
ncurses-libs-5.7-3.20090208.el6.x86_64
ncurses-5.7-3.20090208.el6.x86_64
ncurses-base-5.7-3.20090208.el6.x86_64
```
A possible discrepancy might be that ncurses was not installed correctly. Can you help me out by displaying the content of /my_folder/var/pkg/ncurses-6.0?
```
cat /my_folder/var/pkg/ncurses-6.0
```

**Comment by a-velt** [comment]
Here the /my_folder/var/pkg/ncurses-6.0 file : 

[ncurses-6.0.txt](https://github.com/PacificBiosciences/pitchfork/files/623985/ncurses-6.0.txt)

**Comment by mhsieh** [comment]
The record file looks fine to me. For now, I can only take note on the sl6 issue in the document.

**Comment by mhsieh** [comment]
@a-velt I think I solved this in the latest pitchfork, sorry for the late reply.

**Comment by mhsieh** [comment]
cleaning up old issues, if yo'all find issue I haven't solved, feel free to re-open it, thanks!
