### ISSUE TITLE
Error while making legacy_blasr

### ISSUE THREAD

**Issue by chkcole** [PacificBiosciences/pitchfork#362]
I apologize if this has been posted before, but I couldn't find a thread dealing with this particular error.
I performed the following commands while in my home directory
`~$ git clone https://github.com/PacificBiosciences/pitchfork.git`
`~$ cd pitchfork`
`~/pitchfork$sudo make init`
`~/pitchfork$sudo make legacy_blasr`
Here is a portion of the log:

> [100%] Linking CXX executable ../../../bin/pbmerge
make[4]: Leaving directory '/home/charles/Downloads/pitchfork/workspace/pbbam/build'
[100%] Built target pbmerge
make[3]: Leaving directory '/home/charles/Downloads/pitchfork/workspace/pbbam/build'
make[2]: Leaving directory '/home/charles/Downloads/pitchfork/workspace/pbbam/build'
mkdir -p /home/charles/Downloads/pitchfork/staging/pbbam
cd /home/charles/Downloads/pitchfork/workspace/pbbam/build && tar cf - bin lib | tar xf - -C /home/charles/Downloads/pitchfork/staging/pbbam
tar: bin: Cannot stat: No such file or directory
tar: lib: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
cd /home/charles/Downloads/pitchfork/workspace/pbbam && tar cf - include | tar xf - -C /home/charles/Downloads/pitchfork/staging/pbbam
cd /home/charles/Downloads/pitchfork/staging/pbbam && tar cf - bin lib include | tar xf - -C /home/charles/Downloads/pitchfork/deployment
tar: bin: Cannot stat: No such file or directory
tar: lib: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
cd /home/charles/Downloads/pitchfork/staging/pbbam && find bin lib include ! -type d > /home/charles/Downloads/pitchfork/deployment/var/pkg/pbbam
find: ‘bin’: No such file or directory
find: ‘lib’: No such file or directory
Makefile:44: recipe for target '/home/charles/Downloads/pitchfork/deployment/var/pkg/pbbam' failed
make[1]: *** [/home/charles/Downloads/pitchfork/deployment/var/pkg/pbbam] Error 1
make[1]: Leaving directory '/home/charles/Downloads/pitchfork/ports/pacbio/pbbam'
Makefile:168: recipe for target 'legacy_blasr' failed
make: *** [legacy_blasr] Error 2

Any help would be appreciated.

**Comment by chkcole** [comment]
Also, just to clarify.
The reason why I'm doing this is because I'm trying to get PBHoney working.

**Comment by mhsieh** [comment]
I am more interested in the cmake configuration part of the log, can you send your log to mhsieh @ pacb ?

**Comment by mhsieh** [comment]
By the way, I think you can get a working prebuilt blasr from a smrtanalysis 2.3.0p5 installation/extraction for your PBHoney.

**Comment by chkcole** [comment]
I mailed the logs.
I read somewhere the I specifically needed an older version of the blasr because of the way blasr deals with fasta headers in the new vs old versions.
I'd prefer to get the legacy version working rather than fiddle around with PBHoney just because it might make my life easier if, for whatever reason, I need an old version of blasr in the future.

**Comment by mhsieh** [comment]
Yes, so you should get the prebuilt version of blasr from a smrtanalysis 2.3.0p5 installation.

**Comment by mhsieh** [comment]
Back to the compiling error, I failed to see anything obvious from your log, so can you show us the output for `ls /home/charles/Downloads/pitchfork/workspace/pbbam/build` ?

Thanks

**Comment by chkcole** [comment]
Here is the `ls -lth` of the `workspace/pbbam/build` folder
> total 40K
drwxr-xr-x 4 root root 4.0K Jan  9 17:20 CMakeFiles
drwxr-xr-x 3 root root 4.0K Jan  9 17:17 src
drwxr-xr-x 7 root root 4.0K Jan  9 17:17 tools
-rw-r--r-- 1 root root 1.7K Jan  9 17:17 cmake_install.cmake
-rw-r--r-- 1 root root 6.1K Jan  9 17:17 Makefile
-rw-r--r-- 1 root root  16K Jan  9 17:17 CMakeCache.txt

**Comment by mhsieh** [comment]
can you do this? `find /home/charles/Downloads/pitchfork/workspace/pbbam -name pbmerge` ?

**Comment by mhsieh** [comment]
By the way, were you able to use blasr from the smrtanalysis 2.3.0p5 ?

**Comment by chkcole** [comment]
`find /home/charles/Downloads/pitchfork/workspace/pbbam -name pbmerge`
> /home/charles/Downloads/pitchfork/workspace/pbbam/build/tools/pbmerge
/home/charles/Downloads/pitchfork/workspace/pbbam/tools/pbmerge
/home/charles/Downloads/pitchfork/workspace/pbbam/bin/pbmerge

I have not yet used blasr from smrtanalysis 2.3.0p5.
It's not clear how much overhead its going to take to get that set up.
Is is just a precompiled binary which I download?
If so, could I get the git link to it.
I'm somewhat concerned because the machine I am running this on isn't equipped to act as a server and the hard drive space and memory are somewhat limited so I can't have some huge program running in the background all the time.

**Comment by mhsieh** [comment]
(Regarding the smrtanalysis 2.3.0p5) you can get the 2.3.0p5 distribution from our website (you can also visit this for more information about getting it via command line https://github.com/mhsieh/SMRTAnalysis_2.3.0_install ) basically I recommend installing it but then you can skip the GUI server.

**Comment by mhsieh** [comment]
With regard to the pbbam, did you build this pbbam using this pitchfork clone before (several months earlier)?

**Comment by chkcole** [comment]
I never attempted to build pbbam until yesterday.

**Comment by mhsieh** [comment]
Just found out that's my bad, we need a legacy_pbbam port.

**Comment by chkcole** [comment]
Excellent.
I've got some other stuff I need to do so just send a message when you guys think you have the issue resolved and I'll try and recompile.

**Comment by mhsieh** [comment]
please try using the binary extracted from the distribution first :)

**Comment by chkcole** [comment]
Okay, I installed the distribution.
Where is the binary located within the distribution?
I can't find any READMEs or anything like that

**Comment by mhsieh** [comment]
please do `ldd smrtanalysis/current/analysis/bin/blasr` and see if you need any extra library.

**Comment by chkcole** [comment]
`ldd current/analysis/bin/blasr`
> 	not a dynamic executable

I also tried using as part of the PBHoney pipe and it looks like it might work.
At least it's producing what appears to be a correctly formatted SAM file.

**Comment by mhsieh** [comment]
Good, it's a static build just like I remembered. I think this is is what you need for now. I will change the method to build "legacy blasr".

**Comment by mhsieh** [comment]
the legacy_blasr is now in a branch called legacy_blasr, and you will need to do `make blasr` instead of `make legacy_blasr`

**Comment by mhsieh** [comment]
I am going to close this for now.
