### ISSUE TITLE
Proper way to use pbalign + quiver with pitchfork

### ISSUE THREAD

**Issue by migrau** [PacificBiosciences/pitchfork#380]
Hi all,
I would like to use quiver to polish my assembly but after the SMRTanalysis 3.0+ release, the information here is a bit confusing. 

My original Pacbio reads are in .bax.h5 format and converted to fastq/fasta. I obtained my assembly in fasta format with CANU. I am working on a cluster and I have installed pitchfork (`make blasr && make pbalign && make GenomicConsensu`s) instead SMRT portal, because I just want to use quiver, I would like to avoid the full installation of SMRT software.

**How do you recommend to proceed?** First I tried aligning the fasta pabcio reads to my assembly (with pbalign/basr) but the output bam looks not compatible with quiver ('BASECALLERVERSION' error). I can not either use the .bax.h5 converted to bam (using bax2bam) directly with quiver. I tried to install the old pbalign_legacy and blasr_legacy (to use --forQuiver to obtain the cmp.h5 output from pbalign) but it returns an error during installation.  

Thanks for your help,

**Comment by mhsieh** [comment]
You might want to ask the questions on the individual projects instead. Pitchfork developer(s) are more interested in the build breakages.

**Comment by suryasaha** [comment]
I was able to run pbalign + arrow so this may help
https://github.com/PacificBiosciences/Bioinformatics-Training/issues/42

**Comment by mhsieh** [comment]
cleaning up old issues, if yo'all find issue I haven't solved, feel free to re-open it, thanks!
