### ISSUE TITLE
README note that source build of bam2bam is unavailable at present

### ISSUE THREAD

**Issue by mp15** [PacificBiosciences/pitchfork#381]
After some judicious searches for classes mentioned in bam2bam, I realised you guys haven't made that repository public yet. It might be worth noting in the README that the source build for bam2bam isn't available yet?

**Comment by mjhsieh** [comment]
Which repository do you find the reference to this phrase? Let me see what I can do about it, either a README, or putting some description in the code.

**Comment by mp15** [comment]
I'm not sure quite what you mean but the ```bam2bam``` executable is referenced by pbcoretools for the new barcoding workflow.

**Comment by mhsieh** [comment]
Hi, the best way to get access to our complete software suite is via our software download http://www.pacb.com/support/software-downloads/ . I am closing this issue for now, feel free to re-open it if you need further assistance to solve/unblock your progress.
