### ISSUE TITLE
bam2bax Missing Repository

### ISSUE THREAD

**Issue by paudano** [PacificBiosciences/pitchfork#382]
Pitchfork attempts to download bam2bax from a missing repository:

```
git clone git://github.com/PacificBiosciences/bam2bax /tmp/pitchfork/bam2bax
Initialized empty Git repository in /tmp/pitchfork/bam2bax/.git/
fatal: remote error: 
  Repository not found.
```

github has no PacificBiosciences/bam2bax repository. Was it made private for some reason?

**Comment by mr--white** [comment]
I too have this issue.  pitchfork's 'make bam2bax'  complains:
`"You need to set bam2bax_REPO".  Stop.`
I checked the makefile and sure enough `$(_NAME)_REPO` is not defined.  where can we get it?

**Comment by mhsieh** [comment]
This repository is not publicly available at this moment, sorry for the inconvenience.

**Comment by mr--white** [comment]
Thanks for the reply.  Any ideas on when I should check back?

**Comment by mhsieh** [comment]
Unfortunately I have no idea, but can you find a way to do analysis with the new tools instead of converting new format back to the old format for older tools.

**Comment by paudano** [comment]
From my understanding, PacBio took down the repo to encourage everyone to update their pipelines to use the new BAM format. This is a better way to do it, and the updated tools you are building will read the BAMs. However, you can find bam2bax in an old BLASR build if you really need it.

Update "PATH/TO" for your environment:
```
cd PATH/TO
git clone git@github.com:PacificBiosciences/blasr.git
cd PATH/TO/blasr
git checkout 801ef7e60b

cd PATH/TO/pitchfork

make bam2bax_REPO=PATH/TO/blasr/utils/bam2bax bam2bax
```

**Comment by mhsieh** [comment]
There is no plan to work on the project in question, so I am cleaning up this old issues, feel free to re-open it, if you still need some sort of solution to unblock you guys.
