### ISSUE TITLE
Error when building GenomicConsensus with pitchfork on Ubuntu 16.04

### ISSUE THREAD

**Issue by JudithR** [PacificBiosciences/pitchfork#385]
GenomeConsensus does not build with pitchfork. It fails when trying to install pip:
```
make -j1 -C ports/python/pip do-install
make[1]: Entering directory '/home/ubuntu/software/pitchfork/ports/python/pip'
/home/ubuntu/software/pitchfork/deployment/bin/python get-pip.py --no-setuptools
Requirement already up-to-date: pip in /home/ubuntu/.local/lib/python2.7/site-packages
/home/ubuntu/software/pitchfork/deployment/bin/pip --cache-dir /home/ubuntu/software/pitchfork/.git/pip install setuptools==33.1.1
/bin/bash: /home/ubuntu/software/pitchfork/deployment/bin/pip: No such file or directory
Makefile:16: recipe for target '/home/ubuntu/software/pitchfork/deployment/var/pkg/pip-7.1.2' failed
make[1]: *** [/home/ubuntu/software/pitchfork/deployment/var/pkg/pip-7.1.2] Error 1
make[1]: Leaving directory '/home/ubuntu/software/pitchfork/ports/python/pip'
Makefile:240: recipe for target 'pip' failed
make: *** [pip] Error 2
```
Suggestions are welcome. I checked the recent commits and the hotfix shouldn't affect the install. I tried adding --user to the get-pip.py command but that didn't help either.
J

**Comment by mhsieh** [comment]
Not sure why ~/.local/bin/python is picked, did you specify that?

**Comment by JudithR** [comment]
I didn't specify that, python is /usr/bin/python. .local is in PATH, same happened when I removed it, same thing happened.

**Comment by mhsieh** [comment]
Sorry, I meant did you use HAVE_PYTHON option?

**Comment by mhsieh** [comment]
and is the error the same?

**Comment by JudithR** [comment]
Thx, that fixed it. Was following the instructions on the blasr repo. Didn't see the pitchfork settings.mk suggestion.

**Comment by pb-cdunn** [comment]
Requirement already up-to-date: pip in /home/ubuntu/.local/lib/python2.7/site-packages

That happens when `PYTHONUSERBASE` is  not set, and when **pip** was previously installed with `--user`.

**Comment by mhsieh** [comment]
We can always set PYTHONUSERBASE to something, either it needs to be meaningfully to a folder (as Chris is investigating PYTHONUSERBASE or /dev/null).
