### ISSUE TITLE
Fails on a system that defaults to python3

### ISSUE THREAD

**Issue by paudano** [PacificBiosciences/pitchfork#387]
While installing blasr_libcpp, pitchfork calls:

`/usr/bin/python configure.py`

On systems where `/usr/bin/python` points to python3, it breaks importing a deprecated package, `commands` even if PATH was explicitly setup to run python2 when `python` is executed.

`ModuleNotFoundError: No module named 'commands'`

**Comment by mhsieh** [comment]
DOH!
Please try `make SYSPYTHON=<path_to_python2> blasr_libcpp`  instead of `make blasr_libcpp`.

**Comment by paudano** [comment]
Setting `SYSPYTHON` worked:
`echo SYSPYTHON=/usr/bin/python2 >> settings.mk`

However, there are places where `SYSPYTHON` is not being used. For example, the zlib Makefile (line 17, commit deeefa857e05f4b770217ea41f92d0c87227cef8):

`$(PFHOME)/bin/pitchfork fetch --url $(_URL)/$@`

This calls the pitchfork python script and relies on the shebang line to find python:
`#!/usr/bin/env python`

zlib Makefile (and others) should be calling pitchfork like this:
`$(SYSPYTHON) $(PFHOME)/bin/pitchfork ...`

Since these Makefile include settings.mk from the pitchfork root, this would distribute the setting correctly among the Makefiles.

In order to work around this, I setup a bin directory in another location on my machine, linked `/usr/bin/python2` into it as `python`, then prepended that bin directory to `PATH`. I was able to build blasr only after setting `SYSPYTHON` and modifying `PATH`.

**Comment by mhsieh** [comment]
I will investigate after work.

**Comment by mjhsieh** [comment]
This actually is not Makefile problem, the pitchfork facility is hard-coded to use `/usr/bin/env python`, I guess you should be able to do this with:
```
export PATH=<path that contains system python2 executable>:$PATH
Then do the rest of the build.
```

For system with python3 as system default, I am afraid that I will need to don some planing for the design to change.
