### ISSUE TITLE
installation directory

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/pitchfork#389]
Hi,
when I install with pitchfork e.g. blasr and then I would like to install falcon_polish do I have to change the directory in `make PREFIX=/foo/bar ...`?

Thank you in advance.

Michal

**Comment by mhsieh** [comment]
Hi Michał, please use the same PREFIX setting, if you don't want to type it everytime you want to use run `make` under pitchfork folder, please write it to the settings.mk file.

```
echo "PREFIX=/foo/bar" > settings.mk
```

**Comment by mhsieh** [comment]
cleaning up old issues, if yo'all find issue I haven't solved, feel free to re-open it, thanks!
