### ISSUE TITLE
libpng16.so error while install falcon_polish

### ISSUE THREAD

**Issue by blsfoxfox** [PacificBiosciences/pitchfork#391]
Hi,

I am using pitchfork to install falcon_polish, but get following erros:

cp scripts/sym.out libpng.sym
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -fPIC -I/gpfs0/home/lzb0021/pitchfork/build//include -D_GNU_SOURCE -no-undefined -export-dynamic -version-number 16:21:0   -export-symbols libpng.sym -L/gpfs0/home/lzb0021/pitchfork/build//lib -L/gpfs0/home/lzb0021/pitchfork/build//lib64 -static-libstdc++ -Wl,-rpath,'$ORIGIN/../lib' -o libpng16.la -rpath /gpfs0/home/lzb0021/pitchfork/build/lib png.lo pngerror.lo pngget.lo pngmem.lo pngpread.lo pngread.lo pngrio.lo pngrtran.lo pngrutil.lo pngset.lo pngtrans.lo pngwio.lo pngwrite.lo pngwtran.lo pngwutil.lo    -lm -lz -lm
libtool: link: (cd ".libs" && rm -f "libpng16.so.16" && ln -s "libpng16.so.16.21.0" "libpng16.so.16")
libtool: link: (cd ".libs" && rm -f "libpng16.so" && ln -s "libpng16.so.16.21.0" "libpng16.so")
libtool: link: ar cru .libs/libpng16.a  png.o pngerror.o pngget.o pngmem.o pngpread.o pngread.o pngrio.o pngrtran.o pngrutil.o pngset.o pngtrans.o pngwio.o pngwrite.o pngwtran.o pngwutil.o
libtool: link: ranlib .libs/libpng16.a
libtool: link: ( cd ".libs" && rm -f "libpng16.la" && ln -s "../libpng16.la" "libpng16.la" )
depbase=`echo contrib/tools/pngfix.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
        gcc -DHAVE_CONFIG_H -I.     -fPIC -I/gpfs0/home/lzb0021/pitchfork/build//include -D_GNU_SOURCE -MT contrib/tools/pngfix.o -MD -MP -MF $depbase.Tpo -c -o contrib/tools/pngfix.o contrib/tools/pngfix.c &&\
        mv -f $depbase.Tpo $depbase.Po
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -fPIC -I/gpfs0/home/lzb0021/pitchfork/build//include -D_GNU_SOURCE  -L/gpfs0/home/lzb0021/pitchfork/build//lib -L/gpfs0/home/lzb0021/pitchfork/build//lib64 -static-libstdc++ -Wl,-rpath,'$ORIGIN/../lib' -o pngfix contrib/tools/pngfix.o libpng16.la -lm -lz -lm
libtool: link: gcc -fPIC -I/gpfs0/home/lzb0021/pitchfork/build//include -D_GNU_SOURCE -static-libstdc++ -Wl,-rpath -Wl,\$ORIGIN/../lib -o .libs/pngfix contrib/tools/pngfix.o  -L/gpfs0/home/lzb0021/pitchfork/build//lib -L/gpfs0/home/lzb0021/pitchfork/build//lib64 ./.libs/libpng16.so -lz -lm
gcc: error: ./.libs/libpng16.so: No such file or directory
make[3]: *** [pngfix] Error 1
make[3]: Leaving directory `/gpfs0/home/lzb0021/pitchfork/work/libpng-1.6.21'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/gpfs0/home/lzb0021/pitchfork/work/libpng-1.6.21'
make[1]: *** [/gpfs0/home/lzb0021/pitchfork/work//libpng-1.6.21/.libs/libpng16.so] Error 1
make[1]: Leaving directory `/gpfs0/home/lzb0021/pitchfork/pitchfork/ports/thirdparty/libpng'
make: *** [libpng] Error 2

Could you please provide any suggestions?

Thanks,

**Comment by mjhsieh** [comment]
The error might happen prior to the pasted log, if possible can you share the file /gpfs0/home/lzb0021/pitchfork/build.log (and maybe config.log) with us. You can send it to mhsieh@ or paste it in gist.github.

**Comment by blsfoxfox** [comment]
Hi,

That problem is solved by manually copy libpng16.so to ./libs, however, another error occurs when installing ConsensusCore.
Please check the attachment.

Thanks,

blsfoxfox

**Comment by mhsieh** [comment]
Unfortunately github seemed to ignore the attachment, can you send it to mhsieh at pacb com?

**Comment by mhsieh** [comment]
Thanks I got the attachment, I will take a look and figure out some solution.

**Comment by mhsieh** [comment]
I am sorry that I lost your email in my last computer crash, if this remains a problem in the latest pitchfork, please do reopen this issue.
