### ISSUE TITLE
Error while building Template.cpp.o

### ISSUE THREAD

**Issue by TakashiKoyama** [PacificBiosciences/pitchfork#392]
Hi,

I recently failed ```make GenomicConsensus``` and ```make pbccs``` and both of them failed at bulding same object as follows.
I really appreciate your helps to solve this!

```
[  1%] Building CXX object src/CMakeFiles/cc2.dir/Template.cpp.o
../../src/Template.cpp: In constructor 'PacBio::Consensus::MutatedTemplate::MutatedTemplate(const PacBio::Consensus::AbstractTemplate&, const PacBio::Consensus::Mutation&)':
../../src/Template.cpp:349:31: error: cannot allocate an object of abstract type 'PacBio::Consensus::AbstractTemplate'
     , mutOff_{mut.LengthDiff()}
                               ^
In file included from ../../src/Template.cpp:41:0:
../../include/pacbio/consensus/Template.h:63:7: note:   because the following virtual functions are pure within 'PacBio::Consensus::AbstractTemplate':
 class AbstractTemplate
       ^
../../include/pacbio/consensus/Template.h:68:20: note: 	virtual size_t PacBio::Consensus::AbstractTemplate::Length() const
     virtual size_t Length() const = 0;
                    ^
../../include/pacbio/consensus/Template.h:69:37: note: 	virtual const PacBio::Consensus::TemplatePosition& PacBio::Consensus::AbstractTemplate::operator[](size_t) const
     virtual const TemplatePosition& operator[](size_t i) const = 0;
                                     ^
../../include/pacbio/consensus/Template.h:81:47: note: 	virtual std::unique_ptr<PacBio::Consensus::AbstractRecursor> PacBio::Consensus::AbstractTemplate::CreateRecursor(const PacBio::Data::MappedRead&, double) const
     virtual std::unique_ptr<AbstractRecursor> CreateRecursor(const PacBio::Data::MappedRead& mr,
                                               ^
../../include/pacbio/consensus/Template.h:84:20: note: 	virtual double PacBio::Consensus::AbstractTemplate::ExpectedLLForEmission(PacBio::Consensus::MoveType, uint8_t, uint8_t, PacBio::Consensus::MomentType) const
     virtual double ExpectedLLForEmission(MoveType move, uint8_t prev, uint8_t curr,
                    ^
../../include/pacbio/consensus/Template.h:94:32: note: 	virtual const PacBio::Consensus::ModelConfig& PacBio::Consensus::AbstractTemplate::Config() const
     virtual const ModelConfig& Config() const = 0;
                                ^
make[4]: *** [src/CMakeFiles/cc2.dir/Template.cpp.o] Error 1
make[4]: Leaving directory `/home/samba/Suijitsu_Public/software/pitchfork/workspace/unanimity/_build'
make[3]: *** [src/CMakeFiles/cc2.dir/all] Error 2
make[3]: Leaving directory `/home/samba/Suijitsu_Public/software/pitchfork/workspace/unanimity/_build'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/samba/Suijitsu_Public/software/pitchfork/workspace/unanimity/_build'
make[1]: *** [do-build] Error 2
make[1]: Leaving directory `/home/samba/Suijitsu_Public/software/pitchfork/ports/pacbio/unanimity'
make: *** [unanimity] Error 2
```

**Comment by TakashiKoyama** [comment]
Hi,

I still have the error. Any information is appreciated.

**Comment by mhsieh** [comment]
Hi Takashi, This issue might have been lost in my inbox for too long, have you figured this out? I will help out if needed.

**Comment by palfalvi** [comment]
Hi.
I got the same error recently, I could not solve. Is there any info about this?

**Comment by mhsieh** [comment]
Hi, are you using a recent checkout of pitchfork to your build? and which version of compiler (maybe also the os version) are you using?

**Comment by palfalvi** [comment]
I have CentOS 7.4 and tried with gcc 5.4 and 7.2, too on isoseq_sa5.0.0

I did `make _startover` and now I am getting different errors. I have working pbbam, ccs and blasr, but can't find pbtranscript. 

If I run `make isoseq-core`:

make -C ports/thirdparty/zlib do-install
make[1]: Entering directory `/home/peegee/pacbio/pitchfork/ports/thirdparty/zlib'
make[1]: Nothing to be done for `do-install'.
make[1]: Leaving directory `/home/peegee/pacbio/pitchfork/ports/thirdparty/zlib'
make -C ports/thirdparty/libressl do-install
make[1]: Entering directory `/home/peegee/pacbio/pitchfork/ports/thirdparty/libressl'
make -C /home/peegee/pacbio/pitchfork/workspace/libressl-2.2.5 >& build.log || /home/peegee/pacbio/pitchfork/bin/diewith build.log
make[2]: Entering directory `/home/peegee/pacbio/pitchfork/workspace/libressl-2.2.5'
make[2]: *** No targets specified and no makefile found.  Stop.
make[2]: Leaving directory `/home/peegee/pacbio/pitchfork/workspace/libressl-2.2.5'
make[1]: *** [/home/peegee/pacbio/pitchfork/workspace/libressl-2.2.5/ssl/.libs/libssl.so] Error 1
make[1]: Leaving directory `/home/peegee/pacbio/pitchfork/ports/thirdparty/libressl'
make: *** [openssl] Error 2

If I use `make -i isoseq-core`:

cd /home/peegee/pacbio/pitchfork/workspace/bax2bam/build && /home/peegee/pacbio/isoseq/bin/cmake -E cmake_depends "Unix Makefiles" /home/peegee/pacbio/pitchfork/workspace/bax2bam /home/peegee/pacbio/pitchfork/workspace/bax2bam/tests /home/peegee/pacbio/pitchfork/workspace/bax2bam/build /home/peegee/pacbio/pitchfork/workspace/bax2bam/build/tests /home/peegee/pacbio/pitchfork/workspace/bax2bam/build/tests/CMakeFiles/test_bax2bam.dir/DependInfo.cmake --color=
make[4]: Leaving directory `/home/peegee/pacbio/pitchfork/workspace/bax2bam/build'
make -f tests/CMakeFiles/test_bax2bam.dir/build.make tests/CMakeFiles/test_bax2bam.dir/build
make[4]: Entering directory `/home/peegee/pacbio/pitchfork/workspace/bax2bam/build'
make[4]: Nothing to be done for `tests/CMakeFiles/test_bax2bam.dir/build'.
make[4]: Leaving directory `/home/peegee/pacbio/pitchfork/workspace/bax2bam/build'
[100%] Built target test_bax2bam
make[3]: Leaving directory `/home/peegee/pacbio/pitchfork/workspace/bax2bam/build'
/home/peegee/pacbio/isoseq/bin/cmake -E cmake_progress_start /home/peegee/pacbio/pitchfork/workspace/bax2bam/build/CMakeFiles 0
make[2]: Leaving directory `/home/peegee/pacbio/pitchfork/workspace/bax2bam/build'
make[1]: Leaving directory `/home/peegee/pacbio/pitchfork/ports/pacbio/bax2bam'

I have no idea what is wrong and how to solve it. Do you have any idea?

**Comment by mhsieh** [comment]
Apology for my late response. If you have a working python2.7, you can use `HAVE_PYTHON=<path to the python binary>` in settings.mk to avoid getting into the problem of re-building python.

**Comment by palfalvi** [comment]
I tried with bare python and with conda installed python2.7. The error message is the same. However I realized on `make init` it gives

echo "export   LD_LIBRARY_PATH=/home/peegee/pacbio/isoseq/lib:\$LD_LIBRARY_PATH"  |sed -e 's/::*/:/g' > "/home/peegee/pacbio/isoseq/setup-env.sh"
echo "export PATH=/home/peegee/pacbio/isoseq/bin:\$PATH"|sed -e 's/::*/:/g' >> "/home/peegee/pacbio/isoseq/setup-env.sh"
echo "unset PYTHONPATH"
unset PYTHONPATH

However python is in `$PATH` and can be used for other purposes.

**Comment by mhsieh** [comment]
PYTHONPATH is a special variable, my recommendation is don't touch it, What I meant was "HAVE_PYTHON"

**Comment by palfalvi** [comment]
Sorry i meant i tried ‘HAVE_PYTHON’ with conda and non-conda python2.7 (without touching PYTHONPATH) first. Apperantly disturbing PYTHONPATH is not a way to go.

**Comment by mhsieh** [comment]
Hi Gergo please try do a clean install with `make _starover` command or re-clone the repo and see if you can skip the python compilation. try "make python" first and see if you get any error and I will see what I can help based on the error log.

Please do note that the error you got is different from what Takashi had.

**Comment by mhsieh** [comment]
The genomicconsensus is now available on bioconda - https://bioconda.github.io/recipes/genomicconsensus/README.html
