### ISSUE TITLE
Error compiling blasr 

### ISSUE THREAD

**Issue by GiuliaPasquesi** [PacificBiosciences/pitchfork#400]
I tired to install blasr, but I get this error:
make[1]: Entering directory `/usr/local/pitchfork/ports/thirdparty/hdf5'
/usr/local/pitchfork/bin/pitchfork fetch --url https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.16/src/hdf5-1.8.16.tar.gz
fetching https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.16/src/hdf5-1.8.16.tar.gz
{'url': 'https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.16/src/hdf5-1.8.16.tar.gz', 'subcommand': 'fetch'}
Traceback (most recent call last):
  File "/usr/local/pitchfork/bin/pitchfork", line 327, in <module>
    sys.exit(main())
  File "/usr/local/pitchfork/bin/pitchfork", line 320, in main
    pitchfork(pargs)
  File "/usr/local/pitchfork/bin/pitchfork", line 307, in pitchfork
    _out, _exit, _err = backticks('grep %s MD5SUM | md5sum -c -' % os.path.basename(_prefetch), checked=True)
  File "/usr/local/pitchfork/bin/pitchfork", line 55, in backticks
    errCode, cmd, errorMessage))
Exception: 1 <- `grep hdf5-1.8.16.tar.gz MD5SUM | md5sum -c -`
	md5sum: hdf5-1.8.16.tar.gz: No such file or directory
hdf5-1.8.16.tar.gz: FAILED open or read
md5sum: WARNING: 1 listed file could not be read
make[1]: *** [hdf5-1.8.16.tar.gz] Error 1
make[1]: Leaving directory `/usr/local/pitchfork/ports/thirdparty/hdf5'
make: *** [hdf5] Error 2

I have hdf5 installed in /usr/local/hdf5 (version 1.10.1 ).

What can I do? I tried the installation using make and cmake, but every time I get errors with hdf5.

Thank you in advance

**Comment by mhsieh** [comment]
I am curious about your operating system, was it ubuntu16?

**Comment by mhsieh** [comment]
basically it would be nice if you can share the result of this command:
```
curl -k -L -O https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.16/src/hdf5-1.8.16.tar.gz
```
and see if you can get the file, if not I am going add this to a fall back of wget.

**Comment by GiuliaPasquesi** [comment]
?Thank you so much for your answer. I will get back at you on Monday once I go back to work.


Bests

Giulia

________________________________

**Comment by GiuliaPasquesi** [comment]
I am working on a biolinux 7 (Ubuntu 12.04.2 LTS).
When trying to runt he command (in was the pitchfork folder, but I guess it doesn't matter where), I get this error
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
and nothing is transferring.

Thank you for your help,
Bests
Giulia

**Comment by mhsieh** [comment]
I see, I will take a look on a biolinux7 box.

**Comment by mhsieh** [comment]
You might want to upgrade libssl1.0.0 and curl on your system:
```
sudo apt-get install libssl1.0.0 curl
```

**Comment by mhsieh** [comment]
cleaning up old issues, if yo'all find issue I haven't solved, feel free to re-open it, thanks!
