### ISSUE TITLE
pitchfork python version

### ISSUE THREAD

**Issue by mschatz** [PacificBiosciences/pitchfork#403]
My default version of python on my system is python3, but pitchfork uses python2 syntax causing the build to fail. Can you please make a note of that somewhere?

Thanks!

Mike

**Comment by mhsieh** [comment]
Hi Mike, sorry about my late reply. I will be finishing adding the note in wiki (done-ish) and README.md.
Best,
--mj

**Comment by bhagya-ct** [comment]
I think I got the same issue.

make PREFIX=/tmp/pitchfork blasr
make -f mk/init.mk init
make[1]: Entering directory '/home/mml/pitchfork'
/home/mml/pitchfork/bin/checkSystem
/home/mml/pitchfork/bin/checkCC gcc
mkdir -p "/home/mml/pitchfork/workspace"
mkdir -p "/home/mml/pitchfork/distfiles"
mkdir -p "/home/mml/pitchfork/staging"
mkdir -p "/tmp/pitchfork/bin"
mkdir -p "/tmp/pitchfork/etc"
mkdir -p "/tmp/pitchfork/include"
mkdir -p "/tmp/pitchfork/lib"
mkdir -p "/tmp/pitchfork/lib/pkgconfig"
mkdir -p "/tmp/pitchfork/share"
mkdir -p "/tmp/pitchfork/var/pkg"
echo "export   LD_LIBRARY_PATH=/tmp/pitchfork/lib:\$LD_LIBRARY_PATH"  |sed -e 's/::*/:/g' > "/tmp/pitchfork/setup-env.sh"
echo "export PATH=/tmp/pitchfork/bin:\$PATH"|sed -e 's/::*/:/g' >> "/tmp/pitchfork/setup-env.sh"
echo "unset PYTHONPATH"
unset PYTHONPATH
make[1]: Leaving directory '/home/mml/pitchfork'
touch mk//../initialized.o
make -C ports/thirdparty/zlib do-install
make[1]: Entering directory '/home/mml/pitchfork/ports/thirdparty/zlib'
/home/mml/pitchfork/bin/pitchfork fetch --url https://sourceforge.net/projects/libpng/files/zlib/1.2.8/zlib-1.2.8.tar.gz
fetching https://sourceforge.net/projects/libpng/files/zlib/1.2.8/zlib-1.2.8.tar.gz
{'subcommand': 'fetch', 'url': 'https://sourceforge.net/projects/libpng/files/zlib/1.2.8/zlib-1.2.8.tar.gz'}
Traceback (most recent call last):
  File "/home/mml/pitchfork/bin/pitchfork", line 345, in <module>
    sys.exit(main())
  File "/home/mml/pitchfork/bin/pitchfork", line 338, in main
    pitchfork(pargs)
  File "/home/mml/pitchfork/bin/pitchfork", line 299, in pitchfork
    elif 'curl' in _out[0]:
TypeError: a bytes-like object is required, not 'str'
Makefile:17: recipe for target 'zlib-1.2.8.tar.gz' failed
make[1]: *** [zlib-1.2.8.tar.gz] Error 1
make[1]: Leaving directory '/home/mml/pitchfork/ports/thirdparty/zlib'
Makefile:202: recipe for target 'zlib' failed
make: *** [zlib] Error 2

Please let me know I can I fix this.

Thanks

**Comment by mhsieh** [comment]
This is not the same issue, but did you use the latest version of pitchfork?

**Comment by mhsieh** [comment]
I think my fix several minutes ago should fix your problem.

**Comment by mhsieh** [comment]
cleaning up old issues, if yo'all find issue I haven't solved, feel free to re-open it, thanks!
