### ISSUE TITLE
pitchfork isoseq-core fails on pbbam

### ISSUE THREAD

**Issue by Peterpan2017** [PacificBiosciences/pitchfork#404]
I've been trying to install isoseq-core through pitchfork and keep running into errors.

The error message like this:
`[  39%] Building CXX object src/CMakeFiles/pbbam.dir/MD5.cpp.o
cd /HOME/../pitchfork/workspace/pbbam/build/src && /WORK/app/gcc/4.9.2/bin/g++   -Dpbbam_EXPORTS -I/HOME/../pitchfork/workspace/pbbam/include -I/HOME/../pitchfork/pitchfork_ToFU2_dev/src/htslib/include -I/HOME/../pitchfork/pitchfork_ToFU2_dev/include  -fPIC -I/HOME/../pitchfork/pitchfork_ToFU2_dev/include -D_GNU_SOURCE  -fPIC -I/HOME/../pitchfork/pitchfork_ToFU2_dev/include -D_GNU_SOURCE  -fPIC -I/HOME/../pitchfork/pitchfork_ToFU2_dev/include -D_GNU_SOURCE  -Wall -Wno-unused-local-typedefs -Wno-sign-compare -O2 -g -DNDEBUG -fPIC   -std=gnu++14 -o CMakeFiles/pbbam.dir/MD5.cpp.o -c /HOME/../pitchfork/workspace/pbbam/src/MD5.cpp
/HOME/../pitchfork/workspace/pbbam/src/MD5.cpp:81:5: error：‘hts_md5_context’does not name a type
     hts_md5_context* data_;
     ^
/HOME/../pitchfork/workspace/pbbam/src/MD5.cpp: In constructor 
‘PacBio::BAM::Md5ContextHelper::Md5ContextHelper()’:
/HOME/../pitchfork/workspace/pbbam/src/MD5.cpp:55:11: error：class ‘PacBio::BAM::Md5ContextHelper’ does not have any field named ‘data_’
         : data_(hts_md5_init())
           ^
/HOME/../pitchfork/workspace/pbbam/src/MD5.cpp:55:30: error：‘hts_md5_init’ was not declared in this scope
         : data_(hts_md5_init())
                              ^
/HOME/../pitchfork/workspace/pbbam/src/MD5.cpp:57:13: error：‘data_’ was not declared in this scope
         if (data_ == nullptr)
             ^
/HOME/../pitchfork/workspace/pbbam/src/MD5.cpp: In destructor ‘PacBio::BAM::Md5ContextHelper::~Md5ContextHelper()’:
/HOME/../pitchfork/workspace/pbbam/src/MD5.cpp:63:25: error：‘data_’ was not declared in this scope
         hts_md5_destroy(data_);
                         ^
/HOME/../pitchfork/workspace/pbbam/src/MD5.cpp:63:30: error：‘hts_md5_destroy’ was not declared in this scope
         hts_md5_destroy(data_);
                              ^
/HOME/../pitchfork/workspace/pbbam/src/MD5.cpp:  In member function ‘std::string PacBio::BAM::Md5ContextHelper::Encoded(const string&)’:
/HOME/../pitchfork/workspace/pbbam/src/MD5.cpp:69:24: error：‘data_’ was not declared in this scope
         hts_md5_update(data_, reinterpret_cast<void*>(const_cast<char*>(str.c_str())), str.size());
                        ^
/HOME/../pitchfork/workspace/pbbam/src/MD5.cpp:69:98: error：‘hts_md5_update’ was not declared in this scope
         hts_md5_update(data_, reinterpret_cast<void*>(const_cast<char*>(str.c_str())), str.size());
                                                                                                  ^
/HOME/../pitchfork/workspace/pbbam/src/MD5.cpp:72:36: error：‘hts_md5_final’ was not declared in this scope
         hts_md5_final(digest, data_);
                                    ^
/HOME/../pitchfork/workspace/pbbam/src/MD5.cpp:75:38: error：‘hts_md5_hex’ was not declared in this scope
         hts_md5_hex(hexdigest, digest);
                                      ^
make[4]: *** [src/CMakeFiles/pbbam.dir/MD5.cpp.o] error 1
make[4]: Leaving directory `/HOME/../pitchfork/workspace/pbbam/build'
make[3]: *** [src/CMakeFiles/pbbam.dir/all] error 2
make[3]: Leaving directory `/HOME/../pitchfork/workspace/pbbam/build'
make[2]: *** [all] error 2
make[2]: Leaving directory `/HOME/../pitchfork/workspace/pbbam/build'
make[1]: *** [/HOME/../pitchfork/workspace/pbbam/build/lib/libpbbam.so] error 2
make[1]: Leaving directory `/HOME/../pitchfork/ports/pacbio/pbbam'
make: *** [pbbam] error 2`

How can I fix it and keep installing? 
Thanks,
Xiaohan

FYI:
Tianhe-2（Supercomputer Center）Ubuntu Linux
GCC 5.2.0
CMake 3.5.1
git 2.11.1

**Comment by mhsieh** [comment]
Hi Xiaohan, sorry about my late response, can you checkout the isoseq_sa5.0.0 branch of pitchfork and try again?
```
cd pitchfork
git checkout isoseq_sa5.0.0
echo y | make _startover
make isoseq-core
```

**Comment by mhsieh** [comment]
cleaning up old issues, if yo'all find issue I haven't solved, feel free to re-open it, thanks!
