### ISSUE TITLE
Build Fail due to index error

### ISSUE THREAD

**Issue by zachcp** [PacificBiosciences/pitchfork#405]
Hi Team Pitchfork,

I've encountered the following error when attempting to build software with pitchfork.
```
{'url': 'https://sourceforge.net/projects/libpng/files/zlib/1.2.8/zlib-1.2.8.tar.gz', 'subcommand': 'fetch'}
Traceback (most recent call last):
  File "/software/pitchfork/bin/pitchfork", line 343, in <module>
    sys.exit(main())
  File "/software/pitchfork/bin/pitchfork", line 336, in main
    pitchfork(pargs)
  File "/software/pitchfork/bin/pitchfork", line 306, in pitchfork
    if "CentOS Linux release 7." in _out[0]:
IndexError: list index out of range
make[1]: *** [zlib-1.2.8.tar.gz] Error 1
```

It seems there is an issue in the code detecting the OS and if I simply revert to a commit before that code was added (commit: https://github.com/PacificBiosciences/pitchfork/commit/1045e75b05370904d1331cba1b70049af7481363) I can build just fine.   I believe the destructuring in this code will result in a single item, not a list: `_out, _exit, _err = backticks('lsb_release -d')`  and that is the source of the error.

Thanks for making your software open!
zach cp
I was using Ubuntu 17.10 but encountered this error on CentOS as well.

**Comment by mhsieh** [comment]
Okay I will work on this today.

**Comment by mhsieh** [comment]
Hi Zach, can you provide me the output of the command for `lsb_release -d` in your shell session? Thanks.

**Comment by zachcp** [comment]
```
ubuntu@ip---:~$ lsb_release -d
Description:	Ubuntu 16.04.3 LTS
```

**Comment by mjhsieh** [comment]
Hi Zach, Interesting! Apparently the command `lsb_released -d` inside pitchfork util failed to print out anything... Let me do some hotfix first and analyze the cause for the long-term solution.

**Comment by mjhsieh** [comment]
Will need to test this on ubuntu16 and ubuntu17 .

**Comment by mhsieh** [comment]
I am not able to reproduce the error on ubuntu16/ubuntu17, but taking care of the exceptions is generally a good thing for me.

**Comment by zachcp** [comment]
I can now build off master; thanks.
