### ISSUE TITLE
Problem building unanimity with ptichfork

### ISSUE THREAD

**Issue by stetner** [PacificBiosciences/pitchfork#408]
Hi I seem to be getting a bunch of

expression  '<throw-expression>' is not a constant-expression

errors when trying to compile unanimity with ptichfork.

$ gcc --version
gcc (GCC) 5.2.0gcc

/opt/Modules/binutils/2.28/bin

Any ideas?

Thanks.

Doug

cd /shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/_build && make
make[2]: Entering directory `/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/_build'
make[3]: Entering directory `/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/_build'
make[4]: Entering directory `/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/_build'
make[4]: Leaving directory `/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/_build'
make[4]: Entering directory `/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/_build'
[  1%] Building CXX object src/CMakeFiles/cc2.dir/models/MarginalModelForm.cpp.o
In file included from /shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h:45:0,
                 from /shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/include/pacbio/consensus/ModelConfig.h:49,
                 from /shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/src/models/MarginalModelForm.cpp:44:
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/include/pacbio/data/internal/ConversionFunctions.h: In function 'constexpr uint8_t PacBio::Data::detail::{anonymous}::ASCIIToNCBI4naImpl(char, bool)':
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/include/pacbio/data/internal/ConversionFunctions.h:132:1: error: expression '<throw-expression>' is not a constant-expression
 }
 ^
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/include/pacbio/data/internal/ConversionFunctions.h: In function 'constexpr uint8_t PacBio::Data::detail::{anonymous}::NCBI4naToNCBI2naImpl(uint8_t)':
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/include/pacbio/data/internal/ConversionFunctions.h:175:1: error: expression '<throw-expression>' is not a constant-expression
 }
 ^
In file included from /shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/include/pacbio/consensus/ModelConfig.h:49:0,
                 from /shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/src/models/MarginalModelForm.cpp:44:
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h: At global scope:
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h:119:31: error: explicitly defaulted function 'constexpr PacBio::Data::detail::NCBI2na& PacBio::Data::detail::NCBI2na::operator=(const PacBio::Data::detail::NCBI2na&)' cannot be declared as constexpr because the implicit declaration is not constexpr:
     inline constexpr NCBI2na& operator=(const NCBI2na&) = default;
                               ^
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h:120:31: error: explicitly defaulted function 'constexpr PacBio::Data::detail::NCBI2na& PacBio::Data::detail::NCBI2na::operator=(PacBio::Data::detail::NCBI2na&&)' cannot be declared as constexpr because the implicit declaration is not constexpr:
     inline constexpr NCBI2na& operator=(NCBI2na&&) = default;
                               ^
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h:159:31: error: explicitly defaulted function 'constexpr PacBio::Data::detail::NCBI4na& PacBio::Data::detail::NCBI4na::operator=(const PacBio::Data::detail::NCBI4na&)' cannot be declared as constexpr because the implicit declaration is not constexpr:
     inline constexpr NCBI4na& operator=(const NCBI4na&) = default;
                               ^
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h:160:31: error: explicitly defaulted function 'constexpr PacBio::Data::detail::NCBI4na& PacBio::Data::detail::NCBI4na::operator=(PacBio::Data::detail::NCBI4na&&)' cannot be declared as constexpr because the implicit declaration is not constexpr:
     inline constexpr NCBI4na& operator=(NCBI4na&&) = default;
                               ^
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/src/models/../Recursor.h:196:29:   in constexpr expansion of 'PacBio::Data::detail::NCBI4na::FromASCII(65, 1)'
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/src/models/../Recursor.h:196:29:   in constexpr expansion of 'PacBio::Data::detail::NCBI4na(((int)base), ((int)checkValid))'
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h:196:35: error: 'constexpr uint8_t PacBio::Data::detail::{anonymous}::ASCIIToNCBI4naImpl(char, bool)' called in a constant expression
         : data_{ASCIIToNCBI4naImpl(base, checkValid)}
                                   ^
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/src/models/../Recursor.h:197:90:   in constexpr expansion of 'PacBio::Consensus::TemplatePosition(65, 1.0e+0, 0.0, 0.0, 0.0)'
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/include/pacbio/consensus/ModelConfig.h:86:40:   in constexpr expansion of 'PacBio::Data::detail::NCBI4na::FromASCII(((int)((PacBio::Consensus::TemplatePosition*)this)->PacBio::Consensus::TemplatePosition::Base), 1)'
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/src/models/../Recursor.h:197:90:   in constexpr expansion of 'PacBio::Data::detail::NCBI4na(((int)base), ((int)checkValid))'
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/include/pacbio/data/internal/BaseEncoding.h:196:35: error: 'constexpr uint8_t PacBio::Data::detail::{anonymous}::ASCIIToNCBI4naImpl(char, bool)' called in a constant expression
In file included from /shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/src/models/MarginalModelForm.cpp:54:0:
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/src/models/HelperFunctions.h: In function 'constexpr uint8_t PacBio::Consensus::{anonymous}::EncodeBase(char)':
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/src/models/HelperFunctions.h:88:1: error: expression '<throw-expression>' is not a constant-expression
 }
 ^
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/src/models/HelperFunctions.h: In function 'constexpr uint8_t PacBio::Consensus::{anonymous}::EncodeBase(char, uint8_t)':
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/src/models/HelperFunctions.h:105:1: error: expression '<throw-expression>' is not a constant-expression
 }
 ^
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/src/models/HelperFunctions.h: In function 'constexpr std::pair<char, unsigned char> PacBio::Consensus::{anonymous}::DecodeEmission(uint8_t)':
/shares/common/users/d.stetner/build/unanimity/pitchfork/workspace/unanimity/src/models/HelperFunctions.h:130:1: error: expression '<throw-expression>' is not a constant-expression
 }
 ^
make[4]: *** [src/CMakeFiles/cc2.dir/models/MarginalModelForm.cpp.o] Error 1
...
...

**Comment by richard9292** [comment]
I'm also having this issue (Redhat 6, gcc version 5.3.0).

**Comment by stetner** [comment]
Updated to gcc 7.2.0 and it seemed to work.

**Comment by mhsieh** [comment]
I might need to raise the gcc version check to gcc 6, thanks for reporting! You might want to ask unanimity people about.
