### ISSUE TITLE
git describe --always --dirty=*   failing

### ISSUE THREAD

**Issue by stetner** [PacificBiosciences/pitchfork#409]
I am also hitting this issue.

Thanks for any advice.

CMake Error at cmake/pbcopper-gitsha1.cmake:17 (message):
  Could not determine git sha1 via `git describe --always --dirty=*`
Call Stack (most recent call first):
  CMakeLists.txt:41 (find_git_sha1)

**Comment by mhsieh** [comment]
I think you might need a new git
```
[0]mhsieh@centos6 pbcopper$ git --version
git version 1.7.1
[0]mhsieh@centos6 pbcopper$ git describe --always --dirty=*
error: Malformed value for push.default: simple
error: Must be one of nothing, matching, tracking or current.
fatal: bad config file line 12 in /home/UNIXHOME/mhsieh/.gitconfig
[128]mhsieh@centos6 pbcopper$ module load git/2.8.3
[0]mhsieh@centos6 pbcopper$ git --version
git version 2.8.3
[0]mhsieh@centos6 pbcopper$ git describe --always --dirty=*
5e18b12
```

**Comment by stetner** [comment]
Checked:
 ~/build/unanimity/pitchfork/ports/pacbio/pbcopper

$ git --version
git version 1.7.1
$ git describe --always --dirty=*
a8fe31e*


$ module load git/2.4.3
$ git --version
git version 2.4.3
$ git describe --always --dirty=*
a8fe31e*

**Comment by stetner** [comment]
Interesting that I get a different version though

**Comment by mhsieh** [comment]
so does the newer git resolve the issue? --mj

**Comment by stetner** [comment]
No they both fail in the same way.

**Comment by mhsieh** [comment]
Okay it might need more effort to figure out what error did the cmake see...

**Comment by mhsieh** [comment]
Hi Doug,
    I failed to reproduce the error but I can supply you unofficial binary from my pitchfork test while we can continue to study what happened to build.

--mj

**Comment by stetner** [comment]
Hi Mengjuei,

I worked around the issue manually and got it working on our older cluster.

We also have had a new PacBio Sequel installed, and are getting turnkey compute installed as well, so we will be able to use it to do our work as everything should be preinstalled and supported by Biosoft.

Long story short, I don't really need to follow up on this.  Could be our old os on the cluster or some other incompatibility that caused the issue.

Thanks for your time.

Doug
