### ISSUE TITLE
how to download pbsv source?

### ISSUE THREAD

**Issue by wangyugui** [PacificBiosciences/pitchfork#411]
Hi.

how to download pbsv source?

There is make file in 
https://github.com/PacificBiosciences/pitchfork/tree/master/ports/pacbio/pbsv

and it seems that
$(_NAME)_REPO ?= git://github.com/PacificBiosciences/$(_NAME)

but I failed to download it from git://github.com/PacificBiosciences/pbsv.

Best Regards

**Comment by mhsieh** [comment]
This is for internal test only, sorry for the confusion. Please do follow us on  http://www.pacb.com/support/software-downloads/ since the software you are interested in should be available in the future.
