### ISSUE TITLE
using pitchfork install isoseq-core 

### ISSUE THREAD

**Issue by Sisov** [PacificBiosciences/pitchfork#414]
Dear author:
when I run pitchfork to install isoseq-core,It's appear some errors that:Command "/public1/home/isoseq/software/pitchfork/PacBio/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-GcMLj3-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-PsGYr5-record/install-record.txt --single-version-externally-managed --root /public1/home/isoseq/software/pitchfork/staging/numpy-1.10.2 --compile --install-headers /public1/home/isoseq/software/pitchfork/PacBio/include/site/python2.7/numpy" failed with error code 1 in /tmp/pip-GcMLj3-build/

Since I have tried to using conda to install it .but I do not know how to change the setting.mk files

**Comment by mhsieh** [comment]
Using numpy from conda is not possible in pitchfork, but it's however possible to use conda's python with HAVE_PYTHON=<path_to_conda's_python2.7> in the settings.mk file. 

Let me know which branch of pitchfork and the linux distro/version are you using, so I can confirm then figure out a solution for you.
--mj

**Comment by mhsieh** [comment]
by the way Isoseq3 is now available on bioconda - https://bioconda.github.io/recipes/isoseq3/README.html
