### ISSUE TITLE
Unsupported chemistry ccs error

### ISSUE THREAD

**Issue by moskalenko** [PacificBiosciences/pitchfork#415]
I am still getting the "20180126 20:35:24.174 -|- FATAL      -|- Runner at ../../src/main/ccs.cpp:434 -|- 0x2b51763b7e80|| -|- unsupported sequencing chemistry combination" error when running ccs even after rebuilding with the https://github.com/PacificBiosciences/IsoSeq_SA3nUP/wiki/Installing-IsoSeq-using-pitchfork > 1. "Unsupported 5.0.0 chemistry" error when running pitchfork version of CCS  https://github.com/PacificBiosciences/pitchfork/commit/1d9c99a394a7c497f953394244395ee9a5cf0414 code.

**Comment by moskalenko** [comment]
I have done a clean build/install and can verify the presence of the $PREFIX/chemistry-data-bundle/ directory with the contents from the above patch.

**Comment by Magdoll** [comment]
Hi @moskalenko ,
Please confirm that you have (a) pbbam is updated; (b) activated the new pitchfork env (I recommend installing to a new $PREFIX location) and (c) $SMRT_CHEMISTRY_BUNDLE_DIR is in the env.

All three steps have been written in this little section on issues:https://github.com/PacificBiosciences/IsoSeq_SA3nUP/wiki/Installing-IsoSeq-using-pitchfork#issue

**Comment by moskalenko** [comment]
Thank you @Magdoll. The $SMRT_CHEMISTRY_BUNDLE_DIR wasn't being correctly passed into the container with the tofu2 install. After that was fixed ccs did not thrown an error with the data file in question.
