### ISSUE TITLE
pitchfork asks for gcc version ≥ 6.4 during blasr building

### ISSUE THREAD

**Issue by Absall** [PacificBiosciences/pitchfork#416]
Hello,

I am trying to build blasr. I had make sure that I got all the prerequisites set in my linux system. However, when I tried to build blasr using this command: make PREFIX=/tmp/pitchfork blasr, I got the following error:

```
[ERROR] gcc version needs to be newer than or equal to 6.4
mk/init.mk:38: recipe for target 'sanity' failed
make[1]: *** [sanity] Error 1
make[1]: Leaving directory '/mnt/shared/scratch/ab42303/local_apps/pitchfork'
make: *** No rule to make target 'initialized.o', needed by 'ccache'.  Stop.
```
Why the gcc has to be ≥ 6.4 when pitchfork prerequisite only asks for gcc ≥ 4.9?

**Comment by mhsieh** [comment]
sorry I forgot about the prerequisites. it would also need to be gcc6

**Comment by mhsieh** [comment]
Which linux distro/version do you want to build blasr with? and what blasr version do you need to work with your data? With these information, I should be able to recommend a better solution for you.

**Comment by rob123king** [comment]
I have the same problem. I am trying to run falcon-unzip using the prebuilt binaries supplied but the blasr prebuilt binary is missing a C lib which I can't seem to solve. 

> /home/data/bioinf_resources/programming_tools/falcontest/bin/blasr: error while loading shared libraries: libhdf5.so.10: cannot open shared object file: No such file or directory

So thought would recompile but we have gcc (GCC) 5.4.0 not 6.4.0 and need the bam output that pitchfork provides for blasr

**Comment by mhsieh** [comment]
On the other hand I can lower gcc version requirement now since upstream c++ code have some backward compatibility features added.

**Comment by mhsieh** [comment]
Please contact my email (github handle + @ + pacb.com), if you need the "fix" right now, since we are still verifying the impact of my "fix" to other components.

**Comment by mhsieh** [comment]
it's now possible to use gcc 5.4.0 if you use today's version ade082a935808c75575181f93a8ae44c822488be

**Comment by rob123king** [comment]
Thanks for the change. I'm working with my sys admin to get this last tool working for us and hopefully we can have the full falcon unzip pipeline working.
