### ISSUE TITLE
Disappearing pacbio htslib git

### ISSUE THREAD

**Issue by oomdani** [PacificBiosciences/pitchfork#418]
I tried installing blasr using pitchfork on Ubuntu 16.04 and got the following error:
make[1]: Entering directory '/home/dani/pitchfork/ports/pacbio/htslib'
git clone git://github.com/PacificBiosciences/htslib /home/dani/pitchfork/workspace/htslib
Cloning into '/home/dani/pitchfork/workspace/htslib'...
fatal: remote error: 
  Repository not found.
Makefile:18: recipe for target '/home/dani/pitchfork/workspace/htslib' failed
make[1]: *** [/home/dani/pitchfork/workspace/htslib] Error 128
make[1]: Leaving directory '/home/dani/pitchfork/ports/pacbio/htslib'
Makefile:361: recipe for target 'htslib' failed
make: *** [htslib] Error 2

Where is the repository? I checked the link and got a 404

**Comment by mhsieh** [comment]
Hi, is this pitchfork checkout recent or are you using some special branch? We upgraded htslib version  a while back (Aug, 2017).

**Comment by oomdani** [comment]
The pitchfork is recent but I was trying to install a legacy blasr.

**Comment by mhsieh** [comment]
Did you mean legacy_blasr branch?

**Comment by mhsieh** [comment]
blasr is available on bioconda - https://bioconda.github.io/recipes/blasr/README.html
