### ISSUE TITLE
Quiver install problem

### ISSUE THREAD

**Issue by Teninq** [PacificBiosciences/pitchfork#419]
I've installed Consensuscore successfully, but when I installed Genomicconsensus, it still said that "Could not find suitable distribution for Requirement.parse('ConsensusCore>=0.9.1')". How can I assign  the Consensuscore dependency?

**Comment by mhsieh** [comment]
I will take a look.

**Comment by mhsieh** [comment]
Dear Tenin, are you using a recent checkout of pitchfork? and what is this command say if you run it? ```bin/pitchfork installed```

**Comment by mhsieh** [comment]
GenomicConsensus is now available on bioconda - https://bioconda.github.io/recipes/genomicconsensus/README.html
