### ISSUE TITLE
md5sum issue building with pitchfork

### ISSUE THREAD

**Issue by cokelaer** [PacificBiosciences/pitchfork#420]
From different version of the repository (master), including the latest (8a8bb9356971a6908f9b809603d8cc23c923e0ef), one from nov 2017 (b7bdf01f12bbd43977f140923b0144d75c863348, which used to work a couple of months ago), 

I got this error when building samtools or blasr:

```
make[1]: Leaving directory '/pitchfork'
touch mk//../initialized.o
make -C ports/thirdparty/zlib do-install
make[1]: Entering directory '/pitchfork/ports/thirdparty/zlib'
/pitchfork/bin/pitchfork fetch --url https://sourceforge.net/projects/libpng/files/zlib/1.2.8/zlib-1.2.8.tar.gz
fetching https://sourceforge.net/projects/libpng/files/zlib/1.2.8/zlib-1.2.8.tar.gz
{'url': 'https://sourceforge.net/projects/libpng/files/zlib/1.2.8/zlib-1.2.8.tar.gz', 'subcommand': 'fetch'}
Traceback (most recent call last):
  File "/pitchfork/bin/pitchfork", line 327, in <module>
    sys.exit(main())
  File "/pitchfork/bin/pitchfork", line 320, in main
    pitchfork(pargs)
  File "/pitchfork/bin/pitchfork", line 307, in pitchfork
    _out, _exit, _err = backticks('grep %s MD5SUM | md5sum -c -' % os.path.basename(_prefetch), checked=True)
  File "/pitchfork/bin/pitchfork", line 55, in backticks
    errCode, cmd, errorMessage))
Exception: 1 <- `grep zlib-1.2.8.tar.gz MD5SUM | md5sum -c -`
	zlib-1.2.8.tar.gz: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
Makefile:17: recipe for target 'zlib-1.2.8.tar.gz' failed
make[1]: *** [zlib-1.2.8.tar.gz] Error 1
make[1]: Leaving directory '/pitchfork/ports/thirdparty/zlib'
Makefile:206: recipe for target 'zlib' failed
make: *** [zlib] Error 2
```

any feedbacks appreciated. Thanks

**Comment by mhsieh** [comment]
you can find zlib-1.2.8.tar.gz in /pitchfork/distfiles/zlib/ and see if it's missing or corrupted, old version of pitchfork is very sensitive to curl/wget breakage.

If it indeed is a missing file or corrupted file, try:
1. update curl or wget, maybe ca-certificates as well, then try to build zlib again
2. download the zlib-1.2.8.tar.gz from url in your log using your browser and move the file to /pitchfork/distfiles/zlib/

**Comment by mhsieh** [comment]
blasr is now available on bioconda - https://bioconda.github.io/recipes/blasr/README.html
