### ISSUE TITLE
fatal error: htslib/hts_endian.h: No such file or directory

### ISSUE THREAD

**Issue by GenomeRIK** [PacificBiosciences/pitchfork#421]
Hello,

I am trying to install isoseq-core (isoseq_sa5.0.0) but I keep getting this error:

[  1%] Building CXX object src/CMakeFiles/pbbam.dir/BamRecordImpl.cpp.o
cd /exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19/workspace/pbbam/build/src && ccache /exports/applications/apps/community/roslin/gcc/4.9.2/bin/g++   -Dpbbam_EXPORTS -I/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19/workspace/pbbam/include -I/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19/src/htslib/include -I/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19/include  -fPIC -I/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19//include -D_GNU_SOURCE  -fPIC -I/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19//include -D_GNU_SOURCE  -fPIC -I/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19//include -D_GNU_SOURCE  -Wall -Wno-unused-local-typedefs -Wno-sign-compare -O2 -g -DNDEBUG -fPIC   -std=gnu++14 -o CMakeFiles/pbbam.dir/BamRecordImpl.cpp.o -c /exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19/workspace/pbbam/src/BamRecordImpl.cpp
/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19/workspace/pbbam/src/BamRecordImpl.cpp:51:31: fatal error: htslib/hts_endian.h: No such file or directory
 

#include <htslib/hts_endian.h>
                               ^
compilation terminated.
make[4]: *** [src/CMakeFiles/pbbam.dir/BamRecordImpl.cpp.o] Error 1
make[4]: Leaving directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19/workspace/pbbam/build'
make[3]: *** [src/CMakeFiles/pbbam.dir/all] Error 2
make[3]: Leaving directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19/workspace/pbbam/build'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19/workspace/pbbam/build'
make[1]: *** [/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19/workspace/pbbam/build/lib/libpbbam.so] Error 2
make[1]: Leaving directory `/exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19/ports/pacbio/pbbam'
make: *** [pbbam] Error 2

I tried adding hts_endian.h to the pysam path but it didn't work. Any ideas on why hts_endian.h is missing?

Thank you,
Richard

**Comment by pb-cdunn** [comment]
pbbam was upgraded to use htslib-1.6. `hts_endian.h` was added [here](https://github.com/samtools/htslib/commit/86e32e9e9e7935c62a1adea9cc58298140ca3188):
```
commit 86e32e9e9e7935c62a1adea9cc58298140ca3188
Author: Rob Davies <rmd+git@sanger.ac.uk>
Date:   Wed Jan 25 06:10:01 2017

    Add hts_endian.h to convert little-endian bytes to/from native integers.
```
I *think* the latest htslib (1.7) would work also.

**Comment by GenomeRIK** [comment]
Ok yeah I just installed htslib 1.7-16-g349ad67 and the install works now. Thanks!

**Comment by mhsieh** [comment]
this seems to be a bug to me.

**Comment by mhsieh** [comment]
First of all, you shouldn't need to specifically upgrade htslib for pbbam in isoseq_sa5.0.0 branch, are you using the latest checkout? And why upgrading htslib outside of pitchfork would work at all?

**Comment by GenomeRIK** [comment]
I believe I am using the latest checkout. I just did the git clone. I installed htslib, then added it to my paths, and then ran the install and it worked. 

Although I also changed the settings.mk file to include a path for HAVE_HDF5. I am not sure if that really made a difference though?

I am also specifying the prefix for the install in the settings.mk file.

**Comment by mhsieh** [comment]
do you have these in settings.mk file?
```
bam2fastx_VERSION        = smrtlink-5.0.0
GenomicConsensus_VERSION = 220fc836d58aefc7e3add3636bec798090432727
pbcopper_VERSION         = smrtlink-5.0.0
seqan_VERSION            = smrtlink-5.0.0
unanimity_VERSION        = 96f0b06209c52b2a8db04c1dd35c63ffaf0ee290
blasr_VERSION            = smrtlink-5.0.0
blasr_libcpp_VERSION     = smrtlink-5.0.0
pbfalcon_VERSION         = smrtlink-5.0.0
falcon_polish_VERSION    = smrtlink-5.0.0
kineticsTools_VERSION    = smrtlink-5.0.0
pbalign_VERSION          = smrtlink-5.0.0
pbcommand_VERSION        = smrtlink-5.0.0
pbcoretools_VERSION      = smrtlink-5.0.0
pbdagcon_VERSION         = smrtlink-5.0.0
pbreports_VERSION        = smrtlink-5.0.0
pbsmrtpipe_VERSION       = smrtlink-5.0.0
pbtranscript_VERSION     = smrtlink-5.0.0
pbcore_VERSION           = smrtlink-5.0.0
ConsensusCore_VERSION    = smrtlink-5.0.0
htslib_VERSION           = smrtlink-5.0.0
pbbam_VERSION            = smrtlink-5.0.0
daligner_VERSION         = smrtlink-5.0.0
damasker_VERSION         = smrtlink-5.0.0
dazzdb_VERSION           = smrtlink-5.0.0
dextractor_VERSION       = smrtlink-5.0.0
falcon_kit_VERSION       = smrtlink-5.0.0
pypeFLOW_VERSION         = smrtlink-5.0.0
bax2bam_VERSION          = smrtlink-5.0.0
```

**Comment by GenomeRIK** [comment]
Yes. Copy from my settings.mk file:

bam2fastx_VERSION        = smrtlink-5.0.0
GenomicConsensus_VERSION = 220fc836d58aefc7e3add3636bec798090432727
pbcopper_VERSION         = smrtlink-5.0.0
seqan_VERSION            = smrtlink-5.0.0
unanimity_VERSION        = 96f0b06209c52b2a8db04c1dd35c63ffaf0ee290
blasr_VERSION            = smrtlink-5.0.0
blasr_libcpp_VERSION     = smrtlink-5.0.0
pbfalcon_VERSION         = smrtlink-5.0.0
falcon_polish_VERSION    = smrtlink-5.0.0
kineticsTools_VERSION    = smrtlink-5.0.0
pbalign_VERSION          = smrtlink-5.0.0
pbcommand_VERSION        = smrtlink-5.0.0
pbcoretools_VERSION      = smrtlink-5.0.0
pbdagcon_VERSION         = smrtlink-5.0.0
pbreports_VERSION        = smrtlink-5.0.0
pbsmrtpipe_VERSION       = smrtlink-5.0.0
pbtranscript_VERSION     = smrtlink-5.0.0
pbcore_VERSION           = smrtlink-5.0.0
ConsensusCore_VERSION    = smrtlink-5.0.0
htslib_VERSION           = smrtlink-5.0.0
pbbam_VERSION            = smrtlink-5.0.0
daligner_VERSION         = smrtlink-5.0.0
damasker_VERSION         = smrtlink-5.0.0
dazzdb_VERSION           = smrtlink-5.0.0
dextractor_VERSION       = smrtlink-5.0.0
falcon_kit_VERSION       = smrtlink-5.0.0
pypeFLOW_VERSION         = smrtlink-5.0.0
bax2bam_VERSION          = smrtlink-5.0.0

**Comment by mhsieh** [comment]
https://github.com/PacificBiosciences/pbbam/blob/smrtlink-5.0.0/src/BamRecordImpl.cpp#L51  doesn't have that line. Are you re-using the workspace folder?

**Comment by mhsieh** [comment]
you might want to make _startover to clean everything up since your pbbam checkout is too new for isoseq_sa5.0.0 branch.

**Comment by GenomeRIK** [comment]
What do you mean by reusing the workspace folder? I did a fresh git clone and the ran the instructions for installing Iso-Seq:
https://github.com/PacificBiosciences/IsoSeq_SA3nUP/wiki/Installing-IsoSeq-using-pitchfork

However, during the install it kept stopping and saying that I needed to commit changes. So I would commit then run the "make isoseq-core" again. The time that it did work, it just ran through with now problems.

**Comment by mhsieh** [comment]
I am very curious about the version of your pbbam checkout, it should be at smrtlink-5.0.0 branch, if it's not at smrtlink-5.0.0 branch, something went wrong.

**Comment by GenomeRIK** [comment]
How do I check if my pbbam is at smrtlink-5.0.0 branch?

**Comment by mhsieh** [comment]
```
cd workspace/pbbam
git status
```
I think

**Comment by GenomeRIK** [comment]
Ok I tried that and got this:
# On branch isoseq_sa5.0.0
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   ../LICENSE
#       typechange: ../settings.mk
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)

**Comment by mhsieh** [comment]
you need to change to the directory of pbbam checkout.

**Comment by GenomeRIK** [comment]
I did that. That's what I got plus a bunch of this:

\#       README
\#       bin/.open
\#       bin/2to3
\#       bin/Catrack
\#       bin/DAM2fasta
\#       bin/DB2Falcon
\#       bin/DB2fasta
\#       bin/DBdump
\#       bin/DBdust
..

Too much to copy and paste. 

Same result using:
git -C workspace/pbbam status

**Comment by mhsieh** [comment]
we only need the first several line of the output.

**Comment by mhsieh** [comment]
how about this command?
```
git -C workspace/pbbam rev-parse --short HEAD
```

**Comment by GenomeRIK** [comment]
The command you gave is not working.

When I submit:
 git -c workspace/pbbam rev-parse --short head

I get:
fatal: Needed a single revision

But if I submit:
git -c workspace/pbbam status rev-parse

I get:
\# On branch isoseq_sa5.0.0
nothing to commit, working directory clean

**Comment by mhsieh** [comment]
it was a capital C not lower c.

**Comment by mhsieh** [comment]
```
cd /exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19/workspace/pbbam
git -C workspace/pbbam rev-parse --short HEAD
```
what does it say? Do know that the command is case sensitive.

**Comment by GenomeRIK** [comment]
If I submit the command exactly it does this:

$ git -C workspace/pbbam rev-parse --short HEAD
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

**Comment by mhsieh** [comment]
This means that your git version is old. try my later version of command:
```
cd /exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19/workspace/pbbam
git --short HEAD
```

**Comment by GenomeRIK** [comment]
Ah ok.

$ git rev-parse  --short HEAD
b0b12d0

**Comment by mhsieh** [comment]
This is extremely odd, can you check if there is any reference to htslib/hts_endian.h in /exports/cmvm/eddie/eb/groups/burt_chicken_isoseq/software/git_clone/pitchfork_2018_02_19/workspace/pbbam/src/BamRecordImpl.cpp
?

**Comment by GenomeRIK** [comment]
Oh there isn't. That's strange. So for some reason this time it didn't get the " htslib/hts_endian.h" version of BamRecordImpl.cpp.

I am not sure why it got that before I installed htslib.

I will try it again without giving it the path the htslib to see what happens.

**Comment by mhsieh** [comment]
To be clear, I expect no such reference to hts_endian.h in smrtlink_5.0.0 branch for pbbam. but the error message you post this morning does has such reference, which is the reason why I wanted to verify your pbbam source version.

**Comment by GenomeRIK** [comment]
Yes, I am not sure why I had a different version of BamRecordImpl.cpp in my first tries to install Iso-Seq. I am trying the install again and mimicking my previous environment to see if it happens again.

**Comment by GenomeRIK** [comment]
Ok yeah, if I try to install without giving the path to my htslib installation I get the same issue as I reported originally. 

When I check the BamRecordImpl.cpp file it has the hts_endian.h call:

(More lines before this with code disclaimer)
// Author: Derek Barnett

\#include "PbbamInternalConfig.h"

\#include "pbbam/BamRecordImpl.h"

\#include <algorithm>
\#include <cassert>
\#include <cstddef>
\#include <cstdint>
\#include <cstdlib>
\#include <cstring>
\#include <iostream>
\#include <utility>

\#include <htslib/hts_endian.h>

\#include "BamRecordTags.h"
\#include "MemoryUtils.h"
\#include "pbbam/BamTagCodec.h"

So it seems like if I don't provide the htslib during installation, the installation tries to use an incompatible version of BamRecordImpl.cpp. I think this is the same thing that happened to my collaborator.

**Comment by mhsieh** [comment]
This is getting even weirder, some make rule must be failing silently and didn't finished your git checkout command while cloning pbbam.

**Comment by mhsieh** [comment]
My guess is that your provided htslib has brought something with it, one imagined possibility could be that your non pitchfork htslib brought zlib with and pitchfork zlib happen to interfering with your git.)

What's your linux distro / version ?

**Comment by GenomeRIK** [comment]
NAME="Scientific Linux"
VERSION="7.2 (Nitrogen)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Scientific Linux 7.2 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.2:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"
Scientific Linux release 7.2 (Nitrogen)
Scientific Linux release 7.2 (Nitrogen)
Scientific Linux release 7.2 (Nitrogen)

**Comment by mhsieh** [comment]
I will try to reproduce this, but so far I have been outsmarted by this OS.

**Comment by GenomeRIK** [comment]
Ok if you need me to run your changes on my system to test just let me know.

**Comment by mhsieh** [comment]
Here what I did on my scientific linux minial box using devtoolset, it was successful for me:
```
sudo yum install yum-conf-repos
sudo yum install yum-conf-softwarecollections
sudo yum install devtoolset-7-gcc-c++ devtoolset-7-gcc-gfortran devtoolset-7-gc git19
sudo yum install python-devel
sudo yum install graphviz
sudo yum install freetype-devel
scl enable git19 devtoolset-7 bash
git clone https://github.com/PacificBiosciences/pitchfork.git
cd pitchfork/
git checkout isoseq_sa5.0.0
cat settings.mk.example  > settings.mk
echo "HAVE_PYTHON=/usr/bin/python" >> settings.mk
make isoseq_core
```
I did however need to massage matplotlib Makefile for this gcc7, that commit will be updated tomorrow.

**Comment by mhsieh** [comment]
Isoseq3 is now available on bioconda - https://bioconda.github.io/recipes/isoseq3/README.html
