### ISSUE TITLE
Cannot build blasr

### ISSUE THREAD

**Issue by wkpalan** [PacificBiosciences/pitchfork#422]
Pitchfork Cannot find htslib while building blasr
`/usr/bin/ld: cannot find -lhts`

`g++ -o blasr  -fPIC -I/opt/pb/include -D_GNU_SOURCE  -fPIC -I/opt/pb/include -D_GNU_SOURCE  -fPIC -I/opt/pb/include -D_GNU_SOURCE -O3 -g -DSHA1_7=\"eab53fd\" -std=c++14 -pedantic -Wall -Wextra -Wno-div-by-zero -Wno-overloaded-virtual -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer -I/opt/pb/include/alignment -I/opt/pb/include/hdf -I/opt/pb/include/pbdata  -I/opt/pb/include -I/opt/pb/include -I/opt/pb/include -MF"blasr.d" Blasr.o  -L/opt/pb/lib -L/opt/pb/lib64 -static-libstdc++ -L/opt/pb/lib -L/opt/pb/lib -L/opt/pb/lib -L/opt/pb/lib -L/opt/pb/lib -L/opt/pb -lpbihdf -lblasr -lpbihdf -lpbdata -lpbbam -lhdf5_cpp -lhdf5 -lhts  -lz -lrt -lpthread -ldl`

htslib is present in 
`/opt/pb/src/htslib`

Using latest master branch with clean and fresh start

**Comment by wkpalan** [comment]
Could the changes in blasr makefile to make finding htslib be the cause for this

**Comment by wkpalan** [comment]
Never mind it was an issue with using Ubuntu 16.04 LTS, and it works after upgrading to 17.10.

**Comment by mhsieh** [comment]
Okay, thanks for letting me know.
