### ISSUE TITLE
Can't find <htslib/sam.h>

### ISSUE THREAD

**Issue by jbloom** [PacificBiosciences/pitchfork#423]
When I try to build pitchfork following the instructions, I get the following error message:

```g++ -std=c++14 -pedantic -Wall -Wextra -fPIC -I/home/jbloom/pitchfork/deployment/include -D_GNU_SOURCE  -fPIC -I/home/jbloom/pitchfork/deployment/include -D_GNU_SOURCE  -fPIC -I/home/jbloom/pitchfork/deployment/include -D_GNU_SOURCE -I/home/jbloom/pitchfork/deployment/include -I../pbdata  -I/home/jbloom/pitchfork/deployment/include -I/home/jbloom/pitchfork/deployment/include  -c CCSSequence.cpp -o CCSSequence.o
In file included from /home/jbloom/pitchfork/deployment/include/pbbam/BamRecord.h:18:0,
                 from DNASequence.hpp:15,
                 from FASTQSequence.hpp:4,
                 from SMRTSequence.hpp:11,
                 from CCSSequence.hpp:5,
                 from CCSSequence.cpp:1:
/home/jbloom/pitchfork/deployment/include/pbbam/BamRecordImpl.h:10:24: fatal error: htslib/sam.h: No such file or directory
 #include <htslib/sam.h>
```

Is there some missing path that needs to be included for the compiler to look for libraries?

**Comment by elsherbini** [comment]
I had the exact same issue today. I'm using centos 6.8. I was tring to install pbalign which took 3 or 4 hours to get all the dependencies installed. Now, make pbalign and make blasr say they can't find htslib/sam.h, but make htslib says it's already there.

**Comment by mhsieh** [comment]
okay what was the software you are trying to build with pitchfork?

**Comment by jbloom** [comment]
I got the error building either `bax2bam` or `pbccs`.

**Comment by mhsieh** [comment]
Thanks, I will work on that.

**Comment by elsherbini** [comment]
I got the error with pbalign initially, and blasr errors as well.

**Comment by mhsieh** [comment]
pbbam is now available on bioconda - https://bioconda.github.io/recipes/pbbam/README.html
