### ISSUE TITLE
Two install errors, libopenblas_haswellp and htslib

### ISSUE THREAD

**Issue by twestbrookunh** [PacificBiosciences/pitchfork#425]
Hello - when attempting to build falcon_kit from pitchfork, I first encountered the error:

install: cannot stat 'libopenblas_haswellp-r0.2.18.so': No such file or directory

Similar to an existing trouble ticket. I tried overriding the LIBCORE values to nehalem, but I still received the same error (only with libopenblas_nehalemp).  One of the suggestions was to make use of a system installed version of openblas.  This was all within an anaconda environment, so I added the openblas package, and tried the installation from scratch.  It successfully found the libopenblas, but now I receive the error:

.../pitchfork/deployment/include/pbbam/BamRecordImpl.h:10:10: fatal error: htslib/sam.h: No such file or directory

I have any package within anaconda at my disposal for install - what are the suggested packages and versions to install ahead of time to avoid these compilation issues?  Or do you have any other suggestions?  Thanks for your time!

EDIT: Sorry, just noticed that half of this was a part of an existing bug report.  I'll monitor that one too.  Thanks

**Comment by mhsieh** [comment]
Hi,
    Regarding the openblas issue, did you use the latest version of pitchfork, I think I merged a "fix" yesterday to master, hopefully that make it easier to debug. Another choice is that is you have openblas installed in the system, try assign `HAVE_OPENBLAS = /usr` in your settings.mk file.

**Comment by mhsieh** [comment]
As to the problem with htslib, can you share with me the files of these?
```
pitchfork/ports/thirdparty/htslib/config.log
pitchfork/ports/thirdparty/htslib/build.log
```

**Comment by mhsieh** [comment]
most of falcon stuff is now available on bioconda - https://bioconda.github.io/recipes/pb-falcon/README.html
