### ISSUE TITLE
core dupmp on installing GenomicConsensus

### ISSUE THREAD

**Issue by mchaisso** [PacificBiosciences/pitchfork#426]

**Comment by mchaisso** [comment]
Just recently pulled and tried to make init; make GenomicConsensus

The build runs forever, and then core dumps at the command:

/bin/sh: line 5: 10651 Segmentation fault      LD_LIBRARY_PATH=/net/eichler/vol24/projects/structural_variation/nobackups/projects/HGSVG/phased-sv/pitchfork/workspace/Python-2.7.10:/net/eichler/vol24/projects/structural_variation/nobackups/projects/HGSVG/phased-sv/pitchfork/deployment/lib:/net/eichler/vol24/projects/structural_variation/nobackups/projects/HGSVG/phased-sv/pitchfork/deployment/lib:/net/eichler/vol24/projects/structural_variation/nobackups/projects/HGSVG/phased-sv/pitchfork/deployment/lib:/net/gs/vol3/software/modules-sw/mpc/1.1.0/Linux/RHEL6/x86_64/lib/:/net/gs/vol3/software/modules-sw/mpfr/4.0.1/Linux/RHEL6/x86_64/lib/:/net/gs/vol3/software/modules-sw/gmp/6.1.2/Linux/RHEL6/x86_64/lib/:/net/gs/vol3/software/modules-sw/R/3.0.0/Linux/RHEL6/x86_64/lib64/R/lib:/net/gs/vol3/software/modules-sw/R/3.0.0/Linux/RHEL6/x86_64/lib/R/lib:/net/gs/vol3/software/modules-sw/gcc/8.1.0/Linux/RHEL6/x86_64/lib64/:/net/gs/vol3/software/modules-sw/gcc/8.1.0/Linux/RHEL6/x86_64/lib/:/net/gs/vol3/software/modules-sw/emacs/25.1/Linux/RHEL6/x86_64/lib/:/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/ ./python -E -S -m sysconfig --generate-posix-vars

my environment is minimal:

echo  $PATH
/net/eichler/vol24/projects/structural_variation/nobackups/projects/HGSVG/phased-sv/pitchfork/deployment/bin:/usr/bin:/usr/local/sbin:/bin

echo $LD_LIBRARY_PATH 
/net/eichler/vol24/projects/structural_variation/nobackups/projects/HGSVG/phased-sv/pitchfork/deployment/lib

echo $PYTHONPATH
/net/gs/vol3/software/modules-sw/python/2.7.3/Linux/RHEL6/x86_64/lib/python2.7/site-packages/

**Comment by mhsieh** [comment]
Hi Mark,
   I am back from vacation, I will see what I can do here. Basically we have not tested the build on gcc/8.1.0 yet. So I will need to reproduce it first, but I probably will get a build first for you to test.

**Comment by mhsieh** [comment]
GenomicConsensus is now available in bioconda - https://bioconda.github.io/recipes/genomicconsensus/README.html
