### ISSUE TITLE
Error building Unanimity (make ccs)

### ISSUE THREAD

**Issue by Patr26ck** [PacificBiosciences/pitchfork#429]
Hi all:

I try to follow the instruction here:

unanimity/INSTALL.md at develop · PacificBiosciences/unanimity · GitHub
https://github.com/PacificBiosciences/unanimity/blob/develop/doc/INSTALL.md

to install unanimity

Unfortunately, I encounter errors when running "make ccs"

below is the error msg,
Could any one help to give me some tips ? **Many thanks**!!

[linpei@ourserver build]$ make ccs

......

[ 58%] Building CXX object src/CMakeFiles/unanimity.dir/genomicconsensus/experimental/Settings.cpp.o
In file included from /public1/users/linpei/software/unanimity/src/genomicconsensus/experimental/SettingsOptions.h:5:0,
                 from /public1/users/linpei/software/unanimity/src/genomicconsensus/experimental/Settings.cpp:14:
/public1/users/linpei/software/unanimity/include/pacbio/data/PlainOption.h:20:10: error: 'OptionFlags' in namespace 'PacBio::CLI' does not name a type
     CLI::OptionFlags flags;
          ^~~~~~~~~~~
/public1/users/linpei/software/unanimity/include/pacbio/data/PlainOption.h:25:28: **error**: 'OptionFlags' in namespace 'PacBio::CLI' does not name a type
                 const CLI::OptionFlags& flags = CLI::OptionFlags::DEFAULT)
                            ^~~~~~~~~~~
/public1/users/linpei/software/unanimity/include/pacbio/data/PlainOption.h:25:54: **error**: 'PacBio::CLI::OptionFlags' has not been declared
                 const CLI::OptionFlags& flags = CLI::OptionFlags::DEFAULT)
                                                      ^~~~~~~~~~~

... more errors ...

**Comment by mhsieh** [comment]
Hi, pitchfork is deprecated so we will not spend time on fixing the this building case, however we are in work of the distribution via bioconda, which might be out in weeks.

**Comment by mhsieh** [comment]
pbccs is now available via bioconda
