### ISSUE TITLE
validate graphviz usability for the build.

### ISSUE THREAD

**Issue by mhsieh** [PacificBiosciences/pitchfork#82]
ports/experiment/fontconfig

So we can figure out bug 29501

**Comment by mhsieh** [comment]
How to detect freetype?

**Comment by mjhsieh** [comment]
How to detect fontconfig?

**Comment by pb-cdunn** [comment]
I think it's more common to use a variable like HAS_DOT. We can't install the whole operating system.

This gets to another point: Some things are better installed by whatever works in a particular O/S. It might be a good idea to have a configure-script which handles system dependencies, and it can detect the O/S and cause us to preinstall several libraries, using `yum` where appropriate, etc. Not everything needs its own Makefile.

**Comment by mhsieh** [comment]
Will close this after the validation part is finished.

**Comment by mjhsieh** [comment]
WONT FIX - not going to validate packages unless we are asked to do so
